import { Dimensions, Platform, StyleSheet } from 'react-native'

const { width } = Dimensions.get('window')
const isMobile = width < 768

export const createAssistantProfileStyles = (colors: any, isDark: boolean) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    scrollView: { flex: 1 },
    scrollContent: {
      paddingHorizontal: 12,
      paddingTop: 12,
      paddingBottom: 24,
      gap: 12,
    },

    // Header (preserved)
    headerGradient: {
      paddingTop: 20,
      paddingBottom: 12,
      paddingHorizontal: 20,
    },
    header: {
      paddingTop: Platform.OS === 'ios' ? 50 : 40,
      paddingHorizontal: isMobile ? 16 : 24,
      paddingBottom: isMobile ? 20 : 24,
      borderBottomLeftRadius: isMobile ? 24 : 32,
      borderBottomRightRadius: isMobile ? 24 : 32,
    },
    headerTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 16,
    },
    greeting: {
      fontSize: isMobile ? 12 : 13,
      color:
        colors.sidebar?.text?.muted ||
        (isDark ? '#94a3b8' : 'rgba(255,255,255,0.75)'),
      marginBottom: 2,
    },
    userName: {
      fontSize: isMobile ? 20 : 22,
      fontWeight: '700',
      color: '#ffffff',
      marginBottom: 2,
    },
    role: {
      fontSize: isMobile ? 11 : 12,
      color:
        colors.sidebar?.text?.muted ||
        (isDark ? '#94a3b8' : 'rgba(255,255,255,0.65)'),
      fontWeight: '500',
    },
    profileButton: {
      width: isMobile ? 44 : 48,
      height: isMobile ? 44 : 48,
      borderRadius: isMobile ? 22 : 24,
      borderWidth: 2,
      borderColor: 'rgba(255,255,255,0.2)',
      overflow: 'hidden',
    },
    profileImage: {
      width: '100%',
      height: '100%',
    },
    profileFallback: {
      backgroundColor: colors.accent?.primary || '#0ea5e9',
      justifyContent: 'center',
      alignItems: 'center',
    },
    profileInitials: {
      color: '#ffffff',
      fontSize: isMobile ? 16 : 18,
      fontWeight: '600',
    },
    headerBottom: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    dateContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: 'rgba(255,255,255,0.1)',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 20,
      marginTop: -20,
    },
    dateText: {
      fontSize: isMobile ? 10 : 12,
      color: '#e2e8f0',
      fontWeight: '500',
    },
    logoutButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: 'rgba(239,68,68,0.15)',
      borderColor: 'rgba(239,68,68,0.3)',
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 20,
      marginTop: -18,
    },
    logoutButtonText: {
      color: '#ef4444',
      fontSize: isMobile ? 12 : 13,
      fontWeight: '600',
    },
    headerContent: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    greetingText: {
      fontSize: 12,
      fontWeight: '500',
      opacity: 0.85,
      marginBottom: 2,
      color: isDark ? 'rgba(148,163,184,0.85)' : 'rgba(255,255,255,0.75)',
    },
    roleText: {
      fontSize: 11,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      color: isDark ? 'rgba(148,163,184,0.6)' : 'rgba(255,255,255,0.65)',
    },
    headerActions: { flexDirection: 'row', gap: 8 },
    headerAction: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: 'rgba(255,255,255,0.15)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    logoutHeaderButton: { backgroundColor: 'rgba(239,68,68,0.15)' },

    // Hero Card
    heroCard: {
      backgroundColor: colors.card,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    heroContent: {
      flexDirection: isMobile ? 'column' : 'row',
      alignItems: isMobile ? 'center' : 'flex-start',
      padding: 16,
      gap: 12,
    },
    avatarSection: { alignItems: 'center' },
    avatarButton: {
      width: 80,
      height: 80,
      borderRadius: 40,
      overflow: 'hidden',
      position: 'relative',
    },
    avatarImage: { width: '100%', height: '100%', borderRadius: 40 },
    avatarFallback: {
      width: '100%',
      height: '100%',
      backgroundColor: isDark ? 'rgba(14,165,233,0.2)' : '#e0f2fe',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 40,
      borderWidth: 2,
      borderColor: '#0ea5e9',
    },
    avatarInitials: { fontSize: 28, fontWeight: '800', color: '#0ea5e9' },
    avatarEditBadge: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: '#0ea5e9',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.card,
    },
    avatarLabel: {
      marginTop: 6,
      fontSize: 11,
      fontWeight: '600',
      color: colors.textSecondary,
      textTransform: 'uppercase',
    },
    identitySection: {
      flex: 1,
      alignItems: isMobile ? 'center' : 'flex-start',
    },
    identityName: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.3,
      marginBottom: 2,
    },
    identityEmail: {
      fontSize: 13,
      color: colors.textSecondary,
      marginBottom: 8,
    },
    memberSinceRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    memberSinceText: { fontSize: 11, color: colors.textSecondary },

    // Stats Grid
    statsGrid: {
      flexDirection: 'row',
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: isDark ? 'rgba(255,255,255,0.02)' : '#f8fafc',
    },
    statItem: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 12,
      borderRightWidth: 1,
      borderRightColor: colors.border,
    },
    statItemLast: { borderRightWidth: 0 },
    statIconBox: {
      width: 28,
      height: 28,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 4,
    },
    statValue: { fontSize: 18, fontWeight: '800', color: colors.text },
    statLabel: {
      fontSize: 10,
      fontWeight: '600',
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    memberAvatarImage: {
      width: 40,
      height: 40,
      borderRadius: 20,
    },

    // Section Cards
    sectionCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    sectionHeader: {
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    sectionTitle: { fontSize: 14, fontWeight: '700', color: colors.text },

    // Menu
    menuList: { paddingVertical: 4 },
    menuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    menuItemLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    menuItemText: { fontSize: 14, fontWeight: '600', color: colors.text },

    // Analytics
    analyticsContent: { padding: 14, gap: 14 },
    statusRow: { flexDirection: 'row', gap: 8 },
    statusPill: {
      flex: 1,
      borderRadius: 12,
      paddingVertical: 10,
      alignItems: 'center',
    },
    statusValue: { fontSize: 18, fontWeight: '800' },
    statusLabel: {
      fontSize: 10,
      fontWeight: '600',
      textTransform: 'uppercase',
      marginTop: 2,
    },
    rateRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    rateInfo: { flex: 1 },
    rateTitle: { fontSize: 13, fontWeight: '700', color: colors.text },
    rateSub: { fontSize: 11, color: colors.textSecondary },
    rateBarContainer: { flex: 2 },
    rateBarTrack: {
      height: 6,
      backgroundColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.06)',
      borderRadius: 3,
      overflow: 'hidden',
    },
    rateBarFill: { height: '100%', borderRadius: 3 },

    // Logout
    logoutCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? 'rgba(239,68,68,0.08)' : '#fef2f2',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(239,68,68,0.2)' : 'rgba(239,68,68,0.15)',
      paddingVertical: 14,
      gap: 10,
    },
    logoutText: { fontSize: 15, fontWeight: '700', color: '#ef4444' },

    footer: { alignItems: 'center', paddingVertical: 20, gap: 4 },
    footerText: { fontSize: 13, fontWeight: '600', color: colors.text },
    footerSub: {
      fontSize: 10,
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },

    // Modal styles (compact)
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'flex-end',
    },
    modalContainer: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      maxHeight: '90%',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    modalTitle: { fontSize: 18, fontWeight: '700', color: colors.text },
    modalSubtitle: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
    settingsSection: {
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    settingsSectionTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 12,
    },
    settingsOption: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 10,
    },
    settingsOptionLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    settingsOptionText: { fontSize: 15, fontWeight: '500', color: colors.text },
    settingsOptionValue: { fontSize: 14, color: colors.textSecondary },
    divider: { height: 1, backgroundColor: colors.border, marginVertical: 8 },
    aboutSection: {
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    aboutDescription: { fontSize: 14, color: colors.text, lineHeight: 20 },
    sectionLabel: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 12,
    },
    membersList: { gap: 16 },
    memberItem: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    memberAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.accent.primary + '20',
      justifyContent: 'center',
      alignItems: 'center',
    },
    memberAvatarText: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.accent.primary,
    },
    memberInfo: { flex: 1 },
    memberName: { fontSize: 15, fontWeight: '600', color: colors.text },
    memberRole: { fontSize: 13, color: colors.textSecondary },
    memberEmail: { fontSize: 12, color: colors.accent.primary },
    versionSection: { padding: 20, alignItems: 'center' },
    versionText: { fontSize: 13, color: colors.textSecondary },
    supportBanner: {
      backgroundColor: isDark ? 'rgba(14,165,233,0.1)' : '#e0f2fe',
      borderRadius: 16,
      padding: 16,
      marginHorizontal: 20,
      marginVertical: 16,
      alignItems: 'center',
    },
    supportBannerTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      marginTop: 8,
    },
    supportBannerText: {
      fontSize: 13,
      color: colors.textSecondary,
      marginVertical: 8,
      textAlign: 'center',
    },
    contactSupportButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.accent.primary,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 24,
      gap: 8,
      marginTop: 8,
    },
    contactSupportText: { fontSize: 14, fontWeight: '600', color: '#fff' },

    faqList: { paddingHorizontal: 20 },
    faqItem: {
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      paddingVertical: 12,
    },
    faqQuestion: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    faqQuestionLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
    },
    faqQuestionText: { fontSize: 14, fontWeight: '500', color: colors.text },
    faqAnswer: { paddingTop: 12, paddingLeft: 30 },
    faqAnswerText: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
    },
    versionInfo: { padding: 20, alignItems: 'center' },
    copyrightText: { fontSize: 11, color: colors.textSecondary, marginTop: 4 },
  })
