import { StyleSheet } from 'react-native'
import { ThemeColors } from '../../../Controller/context/ThemeContext'

export const createAnnouncementStyles = (
  colors: ThemeColors,
  isDark: boolean,
  isMobile: boolean,
  isTablet: boolean,
  isDesktop: boolean
) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    headerGradient: {
      paddingTop: isMobile ? 15 : 20,
      paddingBottom: isMobile ? 8 : 12,
      paddingHorizontal: isMobile ? 16 : 24,
    },
    headerContent: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: isMobile ? 12 : 16,
    },
    greetingText: {
      fontSize: isMobile ? 11 : 13,
      fontWeight: '500',
      letterSpacing: 0.3,
      color: colors.sidebar.text.muted,
      opacity: 0.75,
      marginBottom: 2,
    },
    userName: {
      fontSize: isMobile ? 20 : 26,
      fontWeight: '800',
      letterSpacing: -0.8,
      color: '#ffffff',
      marginBottom: 2,
    },
    roleText: {
      fontSize: isMobile ? 10 : 12,
      fontWeight: '500',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      color: colors.sidebar.text.muted,
      opacity: 0.6,
      marginLeft: -4,
    },
    profileButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      borderWidth: 2.5,
      borderColor: 'rgba(255,255,255,0.7)',
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 6,
    },
    characterCounterContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 8,
    },
    characterCounterText: {
      fontSize: 12,
    },
    characterCounterWarning: {
      fontSize: 12,
      color: '#ef4444',
    },
    profileImage: {
      width: '100%',
      height: '100%',
    },
    profileFallback: {
      backgroundColor: 'rgba(255,255,255,0.2)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    profileInitials: {
      color: '#ffffff',
      fontSize: isMobile ? 16 : 18,
      fontWeight: '700',
    },
    dateSection: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: isMobile ? 0 : 0,
    },
    dateContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: isMobile ? 6 : 8,
      paddingVertical: isMobile ? 4 : 6,
    },
    dateText: {
      fontSize: isMobile ? 10 : 12,
      fontWeight: '500',
      letterSpacing: 0.2,
      color: '#ffffff',
      marginLeft: -8,
    },
    headerActions: {
      flexDirection: 'row',
      gap: 12,
    },
    headerAction: {
      width: isMobile ? 36 : 40,
      height: isMobile ? 36 : 40,
      borderRadius: isMobile ? 18 : 20,
      backgroundColor: 'rgba(255, 255, 255, 0.18)',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
    },
    notificationBadge: {
      position: 'absolute',
      top: 8,
      right: 8,
      backgroundColor: '#ef4444',
      borderRadius: 10,
      minWidth: 16,
      height: 16,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#ffffff',
    },
    notificationBadgeText: {
      color: '#ffffff',
      fontSize: 9,
      fontWeight: '700',
      paddingHorizontal: 3,
    },
    // Main Content Grid
    mainContent: {
      flex: 1,
      flexDirection: isMobile ? 'column' : 'row',
      padding: isMobile ? 15 : 20,
      gap: 20,
    },
    leftGrid: {
      flex: isMobile ? undefined : 3,
      width: isMobile ? '100%' : undefined,
      backgroundColor: colors.card,
      borderRadius: 24,
      padding: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.3 : 0.05,
      shadowRadius: 8,
      elevation: 2,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: isMobile ? 15 : 0,
    },
    rightGrid: {
      flex: isMobile ? undefined : 3,
      width: isMobile ? '100%' : undefined,
      backgroundColor: colors.card,
      borderRadius: 24,
      padding: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.3 : 0.05,
      shadowRadius: 8,
      elevation: 2,
      borderWidth: 1,
      borderColor: colors.border,
    },

    leftHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: isMobile ? 12 : 16,
      paddingHorizontal: 4,
    },
    leftTitle: {
      fontSize: isMobile ? 16 : 18,
      fontWeight: '700',
      color: colors.text,
    },
    leftControls: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: isMobile ? 8 : 12,
    },
    announcementCount: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.secondary,
      backgroundColor: isDark ? colors.border : '#f1f5f9',
      paddingHorizontal: isMobile ? 8 : 10,
      paddingVertical: isMobile ? 3 : 4,
      borderRadius: 12,
      overflow: 'hidden',
    },
    leftFilters: {
      flexGrow: 0,
      marginRight: isMobile ? -15 : 0,
    },
    leftFilterButton: {
      paddingHorizontal: isMobile ? 10 : 12,
      paddingVertical: isMobile ? 5 : 6,
      borderRadius: 16,
      backgroundColor: isDark ? colors.border : '#f1f5f9',
      marginRight: isMobile ? 6 : 8,
    },
    leftFilterButtonActive: {
      backgroundColor: colors.accent.primary,
    },
    leftFilterButtonText: {
      fontSize: isMobile ? 11 : 12,
      color: colors.sidebar.text.secondary,
      fontWeight: '500',
    },
    leftFilterButtonTextActive: {
      color: '#ffffff',
    },

    // Paginated List
    paginatedList: {
      flex: 1,
    },
    paginatedItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: isMobile ? 10 : 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      gap: 12,
    },
    paginatedItemActive: {
      backgroundColor: isDark ? `${colors.accent.primary}20` : '#f0f9ff',
      borderLeftWidth: 3,
      borderLeftColor: colors.accent.primary,
    },
    paginatedNumber: {
      width: 28,
      height: 28,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: `${colors.accent.primary}15`,
    },
    paginatedNumberText: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.accent.primary,
    },
    paginatedInfo: {
      flex: 1,
    },
    paginatedTitle: {
      fontSize: isMobile ? 13 : 14,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 4,
    },
    paginatedMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    paginatedDate: {
      fontSize: isMobile ? 10 : 11,
      color: colors.sidebar.text.muted,
    },
    paginatedBadge: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
    },
    paginatedBadgeText: {
      fontSize: 8,
      fontWeight: '700',
      color: '#ffffff',
      textTransform: 'uppercase',
    },
    paginatedCreator: {
      fontSize: isMobile ? 10 : 11,
      color: colors.sidebar.text.muted,
      marginTop: 2,
    },
    paginatedActions: {
      flexDirection: 'row',
      gap: 8,
    },
    paginatedEditButton: {
      width: isMobile ? 28 : 32,
      height: isMobile ? 28 : 32,
      borderRadius: 8,
      backgroundColor: isDark ? `${colors.accent.primary}20` : '#eff6ff',
      justifyContent: 'center',
      alignItems: 'center',
    },
    paginatedDeleteButton: {
      width: isMobile ? 28 : 32,
      height: isMobile ? 28 : 32,
      borderRadius: 8,
      backgroundColor: isDark ? '#ef444420' : '#fef2f2',
      justifyContent: 'center',
      alignItems: 'center',
    },
    paginationContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: isMobile ? 12 : 16,
      paddingTop: 16,
      marginTop: 16,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    paginationButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: isMobile ? 8 : 12,
      paddingVertical: isMobile ? 6 : 8,
      borderRadius: 20,
      backgroundColor: isDark ? colors.card : '#f8fafc',
      borderWidth: 1,
      borderColor: colors.border,
      gap: 4,
    },
    paginationButtonDisabled: {
      opacity: 0.5,
    },
    paginationButtonText: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.accent.primary,
    },
    paginationButtonTextDisabled: {
      color: colors.sidebar.text.muted,
    },
    pageInfo: {
      alignItems: 'center',
    },
    pageInfoText: {
      fontSize: isMobile ? 12 : 14,
      fontWeight: '600',
      color: colors.text,
    },

    // Selected Detail View
    selectedDetailContainer: {
      marginTop: 16,
      padding: isMobile ? 12 : 16,
      backgroundColor: isDark ? colors.card : '#f8fafc',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    selectedDetailHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: isMobile ? 8 : 12,
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    selectedDetailTitle: {
      fontSize: isMobile ? 14 : 16,
      fontWeight: '700',
      color: colors.text,
    },
    selectedDetailContent: {
      gap: 12,
    },
    selectedDetailBadges: {
      flexDirection: 'row',
      gap: isMobile ? 6 : 8,
      marginBottom: 4,
    },
    detailBadge: {
      paddingHorizontal: isMobile ? 8 : 10,
      paddingVertical: isMobile ? 3 : 4,
      borderRadius: 6,
    },
    detailBadgeText: {
      fontSize: isMobile ? 9 : 10,
      fontWeight: '700',
      color: '#ffffff',
      textTransform: 'uppercase',
    },
    selectedDetailMessage: {
      fontSize: isMobile ? 13 : 14,
      color: colors.text,
      lineHeight: isMobile ? 18 : 20,
      marginBottom: isMobile ? 10 : 12,
    },
    selectedDetailFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: isMobile ? 10 : 12,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    selectedDetailDate: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: isMobile ? 4 : 6,
    },
    selectedDetailDateText: {
      fontSize: isMobile ? 10 : 12,
      color: colors.sidebar.text.muted,
    },
    selectedDetailCreator: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 4,
    },
    selectedDetailCreatorText: {
      fontSize: isMobile ? 11 : 13,
      color: colors.sidebar.text.muted,
    },
    selectedDetailActions: {
      flexDirection: 'row',
      gap: isMobile ? 8 : 12,
    },
    selectedDetailEditButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: isMobile ? 10 : 12,
      paddingVertical: isMobile ? 5 : 6,
      backgroundColor: isDark ? `${colors.accent.primary}20` : '#eff6ff',
      borderRadius: 8,
    },
    selectedDetailEditText: {
      fontSize: isMobile ? 10 : 12,
      fontWeight: '600',
      color: colors.accent.primary,
    },
    selectedDetailDeleteButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: isMobile ? 10 : 12,
      paddingVertical: isMobile ? 5 : 6,
      backgroundColor: isDark ? '#ef444420' : '#fef2f2',
      borderRadius: 8,
    },
    selectedDetailDeleteText: {
      fontSize: isMobile ? 10 : 12,
      fontWeight: '600',
      color: '#ef4444',
    },

    // Right side (search)
    rightHeader: {
      marginBottom: isMobile ? 15 : 20,
    },
    searchTitle: {
      fontSize: isMobile ? 16 : 18,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 16,
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? colors.card : '#f8fafc',
      borderRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: isMobile ? 10 : 12,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 16,
    },
    searchInput: {
      flex: 1,
      marginLeft: 12,
      fontSize: isMobile ? 13 : 14,
      color: colors.text,
    },
    searchClearButton: {
      padding: 4,
    },
    searchStats: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    resultsCount: {
      fontSize: isMobile ? 13 : 14,
      color: colors.sidebar.text.secondary,
    },
    resultsHighlight: {
      fontSize: isMobile ? 13 : 14,
      color: colors.accent.primary,
      fontWeight: '600',
    },
    searchResultsContainer: {
      flex: 1,
    },
    searchResultItem: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: isMobile ? 10 : 12,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchResultHeader: {
      marginBottom: 8,
    },
    searchResultTitleContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 0,
    },
    searchResultTitle: {
      fontSize: isMobile ? 13 : 14,
      fontWeight: '600',
      color: colors.text,
      flex: 1,
    },
    searchResultBadges: {
      flexDirection: 'row',
      gap: 4,
      marginLeft: 8,
    },
    searchResultBadge: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
    },
    searchResultBadgeText: {
      fontSize: 8,
      fontWeight: '700',
      color: '#ffffff',
      textTransform: 'uppercase',
    },
    searchResultActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 8,
      marginTop: 4,
    },
    searchResultEditButton: {
      width: isMobile ? 26 : 28,
      height: isMobile ? 26 : 28,
      borderRadius: 6,
      backgroundColor: isDark ? `${colors.accent.primary}20` : '#eff6ff',
      justifyContent: 'center',
      alignItems: 'center',
    },
    searchResultDeleteButton: {
      width: isMobile ? 26 : 28,
      height: isMobile ? 26 : 28,
      borderRadius: 6,
      backgroundColor: isDark ? '#ef444420' : '#fef2f2',
      justifyContent: 'center',
      alignItems: 'center',
    },
    searchResultMessage: {
      fontSize: isMobile ? 12 : 13,
      color: colors.sidebar.text.secondary,
      lineHeight: isMobile ? 16 : 18,
      marginBottom: 8,
    },
    searchResultFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: 8,
    },
    searchResultDate: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    searchResultDateText: {
      fontSize: isMobile ? 10 : 11,
      color: colors.sidebar.text.muted,
    },
    searchResultFullDate: {
      fontSize: isMobile ? 9 : 10,
      color: colors.sidebar.text.muted,
    },
    searchResultCreator: {
      fontSize: isMobile ? 10 : 11,
      color: colors.sidebar.text.muted,
      marginTop: 4,
    },

    // Empty / loading states
    emptyState: {
      alignItems: 'center',
      paddingVertical: isMobile ? 30 : 48,
    },
    emptyStateIcon: {
      width: isMobile ? 60 : 80,
      height: isMobile ? 60 : 80,
      borderRadius: isMobile ? 30 : 40,
      backgroundColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
    },
    emptyStateTitle: {
      fontSize: isMobile ? 16 : 18,
      fontWeight: '600',
      color: colors.sidebar.text.secondary,
      marginBottom: 8,
    },
    emptyStateText: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.muted,
      textAlign: 'center',
      marginBottom: 24,
      maxWidth: 300,
    },
    loadingContainer: {
      padding: 24,
      alignItems: 'center',
      justifyContent: 'center',
    },
    loadingText: {
      marginTop: 8,
      fontSize: isMobile ? 11 : 12,
      color: colors.sidebar.text.secondary,
    },

    // Modal styles
    modernModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modernModalContainer: {
      width: '90%',
      maxWidth: 500,
      backgroundColor: colors.card,
      borderRadius: 24,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.1,
      shadowRadius: 20,
      elevation: 10,
    },
    modernModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: isMobile ? 15 : 20,
      paddingVertical: isMobile ? 12 : 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    modernModalHeaderLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: isMobile ? 8 : 12,
    },
    modernModalIconContainer: {
      width: isMobile ? 32 : 40,
      height: isMobile ? 32 : 40,
      borderRadius: 12,
      backgroundColor: `${colors.accent.primary}15`,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modernModalTitleContainer: {
      gap: 2,
    },
    modernModalTitle: {
      fontSize: isMobile ? 16 : 18,
      fontWeight: '700',
      color: colors.text,
    },
    modernModalSubtitle: {
      fontSize: isMobile ? 10 : 12,
      color: colors.sidebar.text.secondary,
    },
    modernModalCloseButton: {
      width: isMobile ? 32 : 36,
      height: isMobile ? 32 : 36,
      borderRadius: isMobile ? 16 : 18,
      backgroundColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modernModalContent: {
      padding: isMobile ? 15 : 20,
    },
    modernFormGroup: {
      marginBottom: 20,
    },
    modernFormLabel: {
      fontSize: isMobile ? 13 : 14,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 8,
      marginLeft: 4,
    },
    modernFormInput: {
      backgroundColor: isDark ? colors.card : '#f8fafc',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: isMobile ? 12 : 14,
      fontSize: isMobile ? 13 : 14,
      color: colors.text,
    },
    modernTextArea: {
      height: isMobile ? 100 : 120,
      textAlignVertical: 'top',
    },
    modernFormActions: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 24,
    },
    modernSubmitButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: colors.accent.primary,
      paddingVertical: isMobile ? 12 : 14,
      borderRadius: 16,
    },
    modernSubmitButtonDisabled: {
      backgroundColor: colors.sidebar.text.muted,
    },
    modernSubmitButtonText: {
      color: '#ffffff',
      fontSize: isMobile ? 14 : 16,
      fontWeight: '600',
    },
    modernCancelButton: {
      flex: 1,
      backgroundColor: colors.border,
      paddingVertical: isMobile ? 12 : 14,
      borderRadius: 16,
      alignItems: 'center',
    },
    modernCancelButtonText: {
      color: colors.sidebar.text.secondary,
      fontSize: isMobile ? 14 : 16,
      fontWeight: '600',
    },

    // Priority selector
    priorityContainer: {
      flexDirection: 'row',
      gap: isMobile ? 6 : 10,
      marginBottom: 8,
    },
    priorityButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: isMobile ? 6 : 8,
      paddingVertical: isMobile ? 10 : 12,
      paddingHorizontal: isMobile ? 6 : 8,
      borderRadius: 12,
      backgroundColor: isDark ? colors.card : '#f8fafc',
      borderWidth: 1,
      borderColor: colors.border,
    },
    priorityButtonNormalActive: {
      backgroundColor: `${colors.accent.primary}15`,
      borderColor: colors.accent.primary,
    },
    priorityButtonImportantActive: {
      backgroundColor: '#f59e0b15',
      borderColor: '#f59e0b',
    },
    priorityButtonUrgentActive: {
      backgroundColor: '#ef444415',
      borderColor: '#ef4444',
    },
    priorityIndicator: {
      width: isMobile ? 10 : 12,
      height: isMobile ? 10 : 12,
      borderRadius: isMobile ? 5 : 6,
    },
    priorityButtonText: {
      fontSize: isMobile ? 12 : 13,
      fontWeight: '500',
      color: colors.sidebar.text.secondary,
    },
    priorityButtonTextActive: {
      color: colors.text,
      fontWeight: '600',
    },
    priorityHint: {
      fontSize: isMobile ? 11 : 12,
      color: colors.sidebar.text.muted,
      marginTop: 4,
      marginLeft: 4,
      fontStyle: 'italic',
    },
    resultsInfo: {
      paddingHorizontal: isMobile ? 12 : 16,
      marginTop: 8,
      marginBottom: 12,
    },
    resultsText: {
      fontSize: isMobile ? 11 : 13,
      color: colors.sidebar.text.secondary,
    },
    searchResultItemActive: {
      backgroundColor: isDark ? '#1e293b' : '#f1f5f9',
      borderColor: colors.accent.primary,
      borderWidth: 1.5,
      shadowColor: colors.accent.primary,
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    // Glassmorphism Modal
    glassModalOverlay: {
      flex: 1,
      backgroundColor: isDark
        ? 'rgba(15, 23, 42, 0.75)'
        : 'rgba(15, 23, 42, 0.6)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: isMobile ? 16 : 24,
    },
    glassModalContent: {
      width: '100%',
      maxWidth: 520,
      backgroundColor: isDark
        ? 'rgba(255, 255, 255, 0.09)'
        : 'rgba(255, 255, 255, 0.85)',
      borderWidth: 1,
      borderColor: isDark
        ? 'rgba(255, 255, 255, 0.18)'
        : 'rgba(255, 255, 255, 0.6)',
      borderRadius: 28,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 20 },
      shadowOpacity: isDark ? 0.4 : 0.15,
      shadowRadius: 30,
      elevation: 20,
    },
    glassModalContentMobile: {
      maxWidth: '100%',
      borderRadius: 24,
    },
    glassModalTitleMobile: {
      fontSize: 17,
    },
    glassModalClose: {
      padding: 4,
    },
    glassModalBody: {
      padding: isMobile ? 20 : 28,
    },
    glassDetailTitle: {
      fontSize: isDesktop ? 26 : isTablet ? 24 : 22,
      fontWeight: '700',
      lineHeight: 30,
      marginBottom: 16,
      marginTop: 8,
    },
    glassDetailTitleMobile: {
      fontSize: 20,
      lineHeight: 26,
    },

    glassModalOverlayTouch: {
      flex: 1,
    },
    glassModalCentered: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    glassModalContainer: {
      width: '100%',
      maxWidth: 500,
      maxHeight: '85%',
      borderRadius: 28,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.3)',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 15,
    },
    glassModalGradientHeader: {
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      overflow: 'hidden',
    },
    glassModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 16,
    },
    glassModalHeaderLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    glassModalIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(59,130,246,0.15)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    glassModalIconContainerMobile: {
      width: 32,
      height: 32,
    },
    glassModalTitle: {
      fontSize: 20,
      fontWeight: '700',
      letterSpacing: -0.5,
      color: colors.text,
    },
    glassModalSubtitle: {
      fontSize: 13,
      marginTop: 2,
      color: colors.sidebar.text.secondary,
    },
    glassModalCloseButton: {
      padding: 4,
    },
    glassModalScrollContent: {
      paddingBottom: 20,
    },
    glassModalFormSection: {
      marginHorizontal: 16,
      marginVertical: 12,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.2)',
      overflow: 'hidden',
      backgroundColor: 'transparent',
    },
    glassFormGroup: {
      marginHorizontal: 16,
      marginTop: 16,
    },
    glassFormLabel: {
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 8,
      color: colors.text,
    },
    glassPriorityContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    glassPriorityContainerMobile: {
      gap: 8,
    },
    glassPriorityButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 40,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.2)',
      backgroundColor: 'rgba(255,255,255,0.05)',
    },
    glassPriorityButtonMobile: {
      paddingVertical: 8,
      paddingHorizontal: 12,
    },
    glassPriorityIndicator: {
      width: 8,
      height: 8,
      borderRadius: 4,
      marginRight: 8,
    },
    glassPriorityButtonText: {
      fontSize: 14,
      fontWeight: '500',
      color: colors.sidebar.text.secondary,
    },
    glassPriorityButtonTextMobile: {
      fontSize: 12,
    },
    glassFormInput: {
      backgroundColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.05)',
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      fontSize: 16,
      color: colors.text,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.2)',
    },
    glassFormInputMobile: {
      fontSize: 14,
      paddingVertical: 10,
    },
    glassTextArea: {
      minHeight: 100,
      textAlignVertical: 'top',
    },
    glassFormActions: {
      flexDirection: 'row',
      gap: 12,
      marginHorizontal: 16,
      marginTop: 24,
      marginBottom: 16,
    },
    glassFormActionsMobile: {
      flexDirection: 'column',
      gap: 10,
    },
    glassSubmitButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: colors.accent.primary,
      paddingVertical: 12,
      borderRadius: 40,
      shadowColor: colors.accent.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    glassSubmitButtonMobile: {
      paddingVertical: 10,
    },
    glassSubmitButtonDisabled: {
      opacity: 0.5,
    },
    glassSubmitButtonText: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: '600',
    },
    glassSubmitButtonTextMobile: {
      fontSize: 14,
    },
    glassCancelButton: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      borderRadius: 40,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.3)',
      backgroundColor: 'rgba(255,255,255,0.1)',
    },
    glassCancelButtonMobile: {
      paddingVertical: 10,
    },
    glassCancelButtonText: {
      fontSize: 16,
      fontWeight: '500',
      color: colors.sidebar.text.secondary,
    },
    glassCancelButtonTextMobile: {
      fontSize: 14,
    },

    headerGradientMobile: {
      paddingTop: 10,
      paddingBottom: 5,
      paddingHorizontal: 15,
    },
    headerContentMobile: { marginBottom: 15 },
    greetingTextMobile: { fontSize: 12 },
    userNameMobile: { fontSize: 20 },
    roleTextMobile: { fontSize: 10 },
    profileButtonMobile: { width: 40, height: 40, borderRadius: 20 },
    profileInitialsMobile: { fontSize: 16 },
    dateSectionMobile: { marginTop: -5 },
    dateContainerMobile: {
      marginLeft: -5,
      marginTop: -15,
      paddingHorizontal: 5,
      paddingVertical: 4,
    },
    dateTextMobile: { fontSize: 9 },
    headerActionMobile: { width: 36, height: 36, borderRadius: 18 },
    statsGridMobile: { gap: 10, padding: 15, marginTop: -15 },
    statCardMobile: { padding: 12, minWidth: '30%' },
    statIconContainerMobile: { width: 36, height: 36, borderRadius: 10 },
    statNumberMobile: { fontSize: 22 },
    statLabelMobile: { fontSize: 10 },
    mainContentMobile: { flexDirection: 'column', padding: 15, gap: 15 },
    leftGridMobile: { flex: undefined, width: '100%', marginBottom: 15 },
    rightGridMobile: { flex: undefined, width: '100%' },
    leftHeaderMobile: { marginBottom: 12 },
    leftTitleMobile: { fontSize: 16 },
    leftControlsMobile: { gap: 8 },
    announcementCountMobile: {
      fontSize: 12,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    leftFiltersMobile: { marginRight: -15 },
    leftFilterButtonMobile: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      marginRight: 6,
    },
    leftFilterButtonTextMobile: { fontSize: 11 },
    paginatedItemMobile: { padding: 10, gap: 8 },
    paginatedTitleMobile: { fontSize: 13 },
    paginatedDateMobile: { fontSize: 10 },
    paginatedCreatorMobile: { fontSize: 10 },
    paginatedEditButtonMobile: { width: 28, height: 28, borderRadius: 6 },
    paginatedDeleteButtonMobile: { width: 28, height: 28, borderRadius: 6 },
    paginationContainerMobile: { gap: 12, paddingTop: 12, marginTop: 12 },
    paginationButtonMobile: { paddingHorizontal: 8, paddingVertical: 6 },
    pageInfoTextMobile: { fontSize: 12 },
    selectedDetailContainerMobile: { marginTop: 12, padding: 12 },
    selectedDetailHeaderMobile: { marginBottom: 8, paddingBottom: 6 },
    selectedDetailTitleMobile: { fontSize: 14 },
    selectedDetailBadgesMobile: { gap: 6 },
    detailBadgeMobile: { paddingHorizontal: 8, paddingVertical: 3 },
    detailBadgeTextMobile: { fontSize: 9 },
    selectedDetailMessageMobile: {
      fontSize: 13,
      lineHeight: 18,
      marginBottom: 10,
    },
    selectedDetailFooterMobile: { paddingTop: 10 },
    selectedDetailDateMobile: { gap: 4 },
    selectedDetailDateTextMobile: { fontSize: 10 },
    selectedDetailActionsMobile: { gap: 8 },
    selectedDetailEditButtonMobile: {
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    selectedDetailDeleteButtonMobile: {
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    rightHeaderMobile: { marginBottom: 15 },
    searchTitleMobile: { fontSize: 16, marginBottom: 12 },
    searchContainerMobile: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 12,
    },
    searchInputMobile: { marginLeft: 8, fontSize: 13 },
    searchStatsMobile: { marginBottom: 12 },
    resultsCountMobile: { fontSize: 13 },
    searchResultItemMobile: { padding: 10, marginBottom: 6 },
    searchResultTitleMobile: { fontSize: 13 },
    searchResultEditButtonMobile: { width: 26, height: 26, borderRadius: 5 },
    searchResultDeleteButtonMobile: { width: 26, height: 26, borderRadius: 5 },
    searchResultMessageMobile: {
      fontSize: 12,
      lineHeight: 16,
      marginBottom: 6,
    },
    searchResultDateTextMobile: { fontSize: 10 },
    searchResultFullDateMobile: { fontSize: 9 },
    searchResultCreatorMobile: { fontSize: 10 },
    emptyStateMobile: { paddingVertical: 30 },
    emptyStateIconMobile: {
      width: 60,
      height: 60,
      borderRadius: 30,
      marginBottom: 12,
    },
    emptyStateTitleMobile: { fontSize: 16 },
    emptyStateTextMobile: { fontSize: 12, maxWidth: 250 },
    loadingTextMobile: { fontSize: 11 },
    modernModalContainerMobile: { width: '95%', maxWidth: 400 },
    modernModalHeaderMobile: { paddingHorizontal: 15, paddingVertical: 12 },
    modernModalHeaderLeftMobile: { gap: 8 },
    modernModalIconContainerMobile: { width: 32, height: 32, borderRadius: 10 },
    modernModalTitleMobile: { fontSize: 16 },
    modernModalSubtitleMobile: { fontSize: 10 },
    modernModalCloseButtonMobile: { width: 32, height: 32, borderRadius: 16 },
    modernModalContentMobile: { padding: 15 },
    modernFormLabelMobile: { fontSize: 13, marginBottom: 6 },
    modernFormInputMobile: {
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 13,
    },
    priorityContainerMobile: { gap: 6 },
    priorityButtonMobile: { paddingVertical: 10, paddingHorizontal: 6, gap: 6 },
    priorityIndicatorMobile: { width: 10, height: 10, borderRadius: 5 },
    priorityButtonTextMobile: { fontSize: 12 },
    modernFormActionsMobile: { gap: 8, marginTop: 20 },
    modernSubmitButtonMobile: { paddingVertical: 12 },
    modernSubmitButtonTextMobile: { fontSize: 14 },
    modernCancelButtonMobile: { paddingVertical: 12 },
    modernCancelButtonTextMobile: { fontSize: 14 },
    selectedDetailCreatorMobile: { marginTop: 2 },
    selectedDetailCreatorTextMobile: { fontSize: 11 },
    paginatedBadgeContainer: {
      flexDirection: 'row',
      gap: 4,
      marginLeft: 8,
    },
    paginatedTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 4,
    },
  })
}
