import { StyleSheet } from 'react-native'
import { ThemeColors } from '../../../Controller/context/ThemeContext'

export const createAttendanceStyles = (
  colors: ThemeColors,
  isDark: boolean,
  isMobile: boolean,
  isTablet: boolean,
  isDesktop: boolean
) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingBottom: 30,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    loadingCard: {
      backgroundColor: 'rgba(255,255,255,0.1)',
      padding: 40,
      borderRadius: 20,
      alignItems: 'center',
    },
    loadingText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
      marginTop: 16,
    },
    permissionContainer: {
      flex: 1,
      padding: 20,
      justifyContent: 'center',
    },
    permissionCard: {
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 32,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.3 : 0.1,
      shadowRadius: 12,
      elevation: 8,
    },
    permissionIcon: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: '#fee2e2',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
    },
    permissionTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 8,
    },
    permissionText: {
      fontSize: 14,
      color: colors.sidebar.text.secondary,
      textAlign: 'center',
      marginBottom: 24,
      lineHeight: 20,
    },
    permissionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.accent.primary,
      paddingVertical: 14,
      paddingHorizontal: 28,
      borderRadius: 12,
      gap: 8,
    },
    permissionButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
    },
    previewCard: {
      backgroundColor: 'rgba(255,255,255,0.1)',
      borderRadius: 16,
      padding: 20,
      marginTop: 20,
    },
    previewTitle: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 12,
    },
    previewGrid: {
      gap: 8,
    },
    previewItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    previewLabel: {
      color: '#cbd5e1',
      fontSize: 13,
    },
    header: {
      padding: isMobile ? 20 : 24,
      paddingTop: isMobile ? 50 : 60,
      borderBottomLeftRadius: isMobile ? 20 : 24,
      borderBottomRightRadius: isMobile ? 20 : 24,
    },
    headerTop: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 8,
    },
    headerIcon: {
      width: 48,
      height: 48,
      borderRadius: 12,
      backgroundColor: `${colors.accent.primary}20`,
      justifyContent: 'center',
      alignItems: 'center',
    },
    greeting: {
      color: colors.sidebar.text.muted,
      fontSize: 13,
      fontWeight: '500',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    headerTitle: {
      color: '#ffffff',
      fontSize: isMobile ? 22 : 24,
      fontWeight: '700',
    },
    headerSubtitle: {
      color: colors.sidebar.text.muted,
      fontSize: isMobile ? 13 : 14,
      lineHeight: 20,
    },
    scanCard: {
      margin: isMobile ? 16 : 20,
      marginTop: -20,
      borderRadius: 20,
      overflow: 'hidden',
      shadowColor: colors.accent.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 10,
    },
    scanGradient: {
      padding: isMobile ? 24 : 28,
      alignItems: 'center',
    },
    scanIconContainer: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: 'rgba(255,255,255,0.2)',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
    },
    scanCardTitle: {
      color: '#ffffff',
      fontSize: isMobile ? 20 : 22,
      fontWeight: '700',
      marginBottom: 8,
    },
    scanCardSubtitle: {
      color: 'rgba(255,255,255,0.8)',
      fontSize: isMobile ? 13 : 14,
      textAlign: 'center',
      marginBottom: 24,
      lineHeight: 20,
    },
    scanButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#ffffff',
      paddingVertical: isMobile ? 12 : 14,
      paddingHorizontal: isMobile ? 24 : 28,
      borderRadius: 12,
      gap: 8,
    },
    scanButtonText: {
      color: colors.accent.primary,
      fontSize: isMobile ? 15 : 16,
      fontWeight: '700',
    },
    infoCard: {
      backgroundColor: colors.card,
      margin: isMobile ? 16 : 20,
      marginTop: 0,
      borderRadius: 16,
      padding: isMobile ? 16 : 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.3 : 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    infoHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 16,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    infoTitle: {
      fontSize: isMobile ? 15 : 16,
      fontWeight: '700',
      color: colors.text,
    },
    infoGrid: {
      gap: 12,
    },
    infoRow: {
      flexDirection: 'row',
      gap: 12,
    },
    infoItem: {
      flex: 1,
    },
    infoLabel: {
      fontSize: isMobile ? 11 : 12,
      color: colors.sidebar.text.secondary,
      marginBottom: 4,
      textTransform: 'uppercase',
      letterSpacing: 0.3,
    },
    infoValue: {
      fontSize: isMobile ? 13 : 14,
      fontWeight: '600',
      color: colors.text,
    },
    guideCard: {
      backgroundColor: colors.card,
      margin: isMobile ? 16 : 20,
      marginTop: 0,
      borderRadius: 16,
      padding: isMobile ? 16 : 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.3 : 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    guideTitle: {
      fontSize: isMobile ? 15 : 16,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 16,
    },
    guideStep: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 16,
    },
    stepNumber: {
      width: 40,
      height: 40,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    stepContent: {
      flex: 1,
    },
    stepTitle: {
      fontSize: isMobile ? 13 : 14,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 2,
    },
    stepDesc: {
      fontSize: isMobile ? 12 : 13,
      color: colors.sidebar.text.secondary,
    },
    tipsCard: {
      backgroundColor: '#fffbeb',
      margin: isMobile ? 16 : 20,
      marginTop: 0,
      borderRadius: 16,
      padding: isMobile ? 14 : 16,
      marginBottom: 100,
    },
    tipsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 12,
    },
    tipsTitle: {
      fontSize: isMobile ? 13 : 14,
      fontWeight: '700',
      color: '#92400e',
    },
    tipItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    tipText: {
      fontSize: isMobile ? 12 : 13,
      color: '#a16207',
    },
    scannerContainer: {
      flex: 1,
      backgroundColor: '#000',
    },
    scannerLoading: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.9)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 10,
    },
    scannerLoadingText: {
      color: '#fff',
      fontSize: 16,
      marginTop: 16,
    },
    camera: {
      ...StyleSheet.absoluteFillObject,
    },
    scannerOverlay: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: 'center',
      alignItems: 'center',
    },
    scannerFrame: {
      width: 250,
      height: 250,
      justifyContent: 'center',
      alignItems: 'center',
    },
    cornerTL: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: 40,
      height: 40,
      borderTopWidth: 4,
      borderLeftWidth: 4,
      borderColor: colors.accent.primary,
    },
    cornerTR: {
      position: 'absolute',
      top: 0,
      right: 0,
      width: 40,
      height: 40,
      borderTopWidth: 4,
      borderRightWidth: 4,
      borderColor: colors.accent.primary,
    },
    cornerBL: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      width: 40,
      height: 40,
      borderBottomWidth: 4,
      borderLeftWidth: 4,
      borderColor: colors.accent.primary,
    },
    cornerBR: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 40,
      height: 40,
      borderBottomWidth: 4,
      borderRightWidth: 4,
      borderColor: colors.accent.primary,
    },
    scannerInstruction: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
      marginTop: 40,
      textShadowColor: 'rgba(0,0,0,0.5)',
      textShadowOffset: { width: 0, height: 2 },
      textShadowRadius: 4,
    },
    locationBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: `${colors.accent.primary}E6`,
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 20,
      marginTop: 20,
      gap: 8,
    },
    locationBadgeText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '600',
    },
    scannerHeader: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: isMobile ? 50 : 60,
      paddingBottom: 20,
    },
    closeScannerBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.2)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    scannerHeaderTitle: {
      color: '#fff',
      fontSize: 18,
      fontWeight: '600',
    },
    resultOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'flex-end',
    },
    resultCard: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 24,
      paddingTop: 32,
      maxHeight: '85%',
    },
    resultIconContainer: {
      alignItems: 'center',
      marginBottom: 20,
    },
    resultIconGradient: {
      width: 80,
      height: 80,
      borderRadius: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    resultTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: '#059669',
      textAlign: 'center',
      marginBottom: 8,
    },
    resultTitleError: {
      fontSize: 24,
      fontWeight: '700',
      color: '#dc2626',
      textAlign: 'center',
      marginBottom: 8,
    },
    resultMessage: {
      fontSize: 16,
      color: '#059669',
      textAlign: 'center',
      marginBottom: 20,
    },
    resultMessageError: {
      fontSize: 16,
      color: '#dc2626',
      textAlign: 'center',
      marginBottom: 20,
    },
    verifiedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#d1fae5',
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 20,
      gap: 6,
      marginBottom: 20,
    },
    verifiedText: {
      color: '#059669',
      fontSize: 14,
      fontWeight: '600',
    },
    eventDetailsCard: {
      backgroundColor: colors.border,
      borderRadius: 12,
      padding: 16,
      marginBottom: 20,
    },
    eventName: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 8,
    },
    eventMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 4,
    },
    eventMetaText: {
      fontSize: 13,
      color: colors.sidebar.text.secondary,
    },
    studentDetails: {
      backgroundColor: colors.border,
      borderRadius: 12,
      padding: 16,
      marginBottom: 20,
    },
    detailsTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 12,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    detailRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    detailLabel: {
      fontSize: 13,
      color: colors.sidebar.text.secondary,
    },
    detailValue: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
    },
    doneButton: {
      backgroundColor: colors.accent.primary,
      paddingVertical: 16,
      borderRadius: 12,
      alignItems: 'center',
    },
    doneButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '700',
    },
    distanceWarning: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#fef3c7',
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 8,
      gap: 6,
      marginBottom: 20,
    },
    distanceText: {
      color: '#92400e',
      fontSize: 13,
      fontWeight: '500',
    },
    errorActions: {
      gap: 12,
    },
    retryButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.accent.primary,
      paddingVertical: 14,
      borderRadius: 12,
      gap: 8,
    },
    retryButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
    },
    cancelResultButton: {
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: 'center',
    },
    cancelResultText: {
      color: colors.sidebar.text.secondary,
      fontSize: 16,
      fontWeight: '600',
    },
    permissionAlertCard: {
      backgroundColor: colors.card,
      margin: isMobile ? 16 : 20,
      marginTop: -10,
      borderRadius: 16,
      padding: 13,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.3 : 0.05,
      shadowRadius: 8,
      elevation: 2,
      marginBottom: 20,
    },
    permissionAlertHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 12,
    },
    permissionAlertTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: '#92400e',
    },
    permissionAlertItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.border,
      padding: 12,
      borderRadius: 12,
      marginBottom: 8,
    },
    permissionAlertIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    permissionAlertContent: {
      flex: 1,
      marginLeft: 12,
    },
    permissionAlertItemTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
    },
    permissionAlertItemDesc: {
      fontSize: 12,
      color: colors.sidebar.text.secondary,
      marginTop: 2,
    },
    scanButtonDisabled: {
      backgroundColor: '#f1f5f9',
    },
    scanButtonTextDisabled: {
      color: '#9ca3af',
    },
    permissionOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.7)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    permissionModal: {
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 28,
      width: '100%',
      maxWidth: 340,
      alignItems: 'center',
    },
    permissionModalIcon: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: '#fee2e2',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
    },
    permissionModalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 12,
      textAlign: 'center',
    },
    permissionModalText: {
      fontSize: 14,
      color: colors.sidebar.text.secondary,
      textAlign: 'center',
      marginBottom: 24,
      lineHeight: 20,
    },
    permissionModalButtons: {
      flexDirection: 'row',
      gap: 12,
      width: '100%',
    },
    permissionModalCancel: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: 'center',
      backgroundColor: colors.border,
    },
    permissionModalCancelText: {
      color: colors.sidebar.text.secondary,
      fontSize: 15,
      fontWeight: '600',
    },
    permissionModalEnable: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.accent.primary,
      paddingVertical: 14,
      borderRadius: 12,
      gap: 8,
    },
    permissionModalEnableText: {
      color: '#fff',
      fontSize: 15,
      fontWeight: '600',
    },
  })
}
