import { StyleSheet } from 'react-native'
import { ThemeColors } from '../../../Controller/context/ThemeContext'

export const createProfileStyles = (
  colors: ThemeColors,
  isDark: boolean,
  isMobile: boolean,
  isTablet: boolean,
  isDesktop: boolean
) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    profileCard: {
      backgroundColor: colors.card,
      borderRadius: 24,
      padding: isMobile ? 20 : 24,
      alignItems: 'center',
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.3 : 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    avatarContainer: {
      position: 'relative',
      marginBottom: 16,
    },
    avatar: {
      width: isMobile ? 80 : 100,
      height: isMobile ? 80 : 100,
      borderRadius: isMobile ? 40 : 50,
      backgroundColor: colors.accent.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    avatarText: {
      fontSize: isMobile ? 32 : 40,
      fontWeight: '600',
      color: '#ffffff',
    },
    cameraIcon: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: colors.accent.primary,
      width: isMobile ? 28 : 32,
      height: isMobile ? 28 : 32,
      borderRadius: isMobile ? 14 : 16,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 3,
      borderColor: colors.card,
    },
    name: {
      fontSize: isMobile ? 18 : 20,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 4,
    },
    id: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.secondary,
      marginBottom: 4,
    },
    course: {
      fontSize: isMobile ? 14 : 16,
      fontWeight: '500',
      color: colors.text,
      marginBottom: 2,
    },
    yearLevel: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.secondary,
    },
    section: {
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: isMobile ? 14 : 16,
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: isDark ? 0.3 : 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    eventsCount: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.secondary,
    },
    loading: {
      marginVertical: 20,
    },
    emptyState: {
      alignItems: 'center',
      paddingVertical: 24,
    },
    emptyStateText: {
      fontSize: isMobile ? 13 : 14,
      color: colors.sidebar.text.secondary,
      marginTop: 8,
      textAlign: 'center',
    },
    emptyStateSubtext: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.muted,
      marginTop: 8,
      textAlign: 'center',
    },
    eventsList: {
      gap: 12,
    },
    eventItem: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
    },
    attendedEventItem: {
      borderLeftWidth: 3,
      borderLeftColor: '#10b981',
    },
    eventIcon: {
      width: 36,
      height: 36,
      borderRadius: 8,
      backgroundColor: isDark ? `${colors.accent.primary}20` : '#fee2e2',
      justifyContent: 'center',
      alignItems: 'center',
    },
    eventDetails: {
      flex: 1,
    },
    eventTitle: {
      fontSize: isMobile ? 14 : 15,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 2,
    },
    eventDate: {
      fontSize: isMobile ? 11 : 12,
      color: colors.sidebar.text.secondary,
      marginBottom: 2,
    },
    deadlineText: {
      fontSize: isMobile ? 10 : 11,
      color: '#dc2626',
      fontWeight: '500',
    },
    scannedAtText: {
      fontSize: isMobile ? 11 : 12,
      color: '#10b981',
      marginTop: 4,
      fontWeight: '500',
    },
    moreEventsText: {
      fontSize: isMobile ? 12 : 13,
      color: colors.accent.primary,
      marginTop: 8,
      textAlign: 'center',
    },
    menu: {
      marginTop: 4,
    },
    menuText: {
      flex: 1,
      fontSize: isMobile ? 14 : 15,
      color: colors.text,
      marginLeft: 12,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 16,
    },
    aboutModal: {
      backgroundColor: colors.card,
      borderRadius: 24,
      width: '100%',
      maxHeight: '80%',
      padding: 20,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    modalTitle: {
      fontSize: isMobile ? 16 : 18,
      fontWeight: '700',
      color: colors.text,
    },
    modalSubtitle: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.secondary,
      marginTop: 2,
    },
    aboutContent: {
      gap: 20,
    },
    aboutSection: {
      marginBottom: 16,
    },
    aboutDescription: {
      fontSize: isMobile ? 13 : 14,
      color: colors.text,
      lineHeight: 20,
    },
    organizationName: {
      fontSize: isMobile ? 14 : 16,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 12,
    },
    membersList: {
      gap: 12,
    },
    memberItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    memberAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.accent.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    memberAvatarImage: {
      width: 44,
      height: 44,
      borderRadius: 22,
    },
    memberAvatarText: {
      fontSize: 18,
      fontWeight: '600',
      color: '#ffffff',
    },
    memberInfo: {
      flex: 1,
    },
    memberName: {
      fontSize: isMobile ? 14 : 15,
      fontWeight: '600',
      color: colors.text,
    },
    memberRole: {
      fontSize: isMobile ? 11 : 12,
      color: colors.accent.primary,
      marginTop: 2,
    },
    memberEmail: {
      fontSize: isMobile ? 10 : 11,
      color: colors.sidebar.text.secondary,
      marginTop: 2,
    },
    sectionLabel: {
      fontSize: isMobile ? 13 : 14,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 8,
    },
    submittedToCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.border,
      borderRadius: 12,
      padding: 12,
      gap: 12,
    },
    submittedToInfo: {
      flex: 1,
    },
    submittedToName: {
      fontSize: isMobile ? 14 : 15,
      fontWeight: '600',
      color: colors.text,
    },
    submittedToDepartment: {
      fontSize: isMobile ? 12 : 13,
      color: colors.sidebar.text.secondary,
      marginTop: 2,
    },
    submittedToInstitution: {
      fontSize: isMobile ? 11 : 12,
      color: colors.sidebar.text.muted,
      marginTop: 2,
    },
    versionSection: {
      alignItems: 'center',
      marginTop: 8,
    },
    versionText: {
      fontSize: isMobile ? 11 : 12,
      color: colors.sidebar.text.muted,
    },
    imageOptions: {
      backgroundColor: colors.card,
      borderRadius: 24,
      padding: 20,
      width: '100%',
      maxWidth: 400,
    },
    optionsTitle: {
      fontSize: isMobile ? 16 : 18,
      fontWeight: '600',
      color: colors.text,
      textAlign: 'center',
      marginBottom: 20,
    },
    optionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 12,
      backgroundColor: colors.border,
      marginBottom: 8,
    },
    optionText: {
      fontSize: isMobile ? 14 : 15,
      color: colors.text,
    },
    removeButton: {
      backgroundColor: '#fee2e2',
    },
    removeText: {
      color: '#dc2626',
    },
    cancelButton: {
      marginTop: 12,
      paddingVertical: 14,
      alignItems: 'center',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    cancelText: {
      fontSize: isMobile ? 14 : 15,
      fontWeight: '600',
      color: colors.sidebar.text.secondary,
    },
    tabContainer: {
      flexDirection: 'row',
      marginBottom: 16,
      backgroundColor: colors.border,
      borderRadius: 12,
      padding: 4,
    },
    tab: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 8,
      gap: 6,
    },
    activeTab: {
      backgroundColor: colors.card,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: isDark ? 0.3 : 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    tabText: {
      fontSize: isMobile ? 13 : 14,
      fontWeight: '600',
      color: colors.sidebar.text.secondary,
    },
    activeTabText: {
      color: colors.text,
    },
    badge: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 12,
      marginLeft: 4,
    },
    badgeText: {
      fontSize: isMobile ? 11 : 12,
      fontWeight: '700',
    },
    penaltyBadge: {
      position: 'absolute',
      top: 12,
      right: 12,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#ef4444',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 16,
      gap: 4,
    },
    penaltyBadgeText: {
      color: '#ffffff',
      fontSize: isMobile ? 11 : 12,
      fontWeight: '600',
    },
    menuIconContainer: {
      position: 'relative',
    },
    penaltyCard: {
      backgroundColor: colors.border,
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
    },
    penaltyCardOverdue: {
      borderLeftColor: '#dc2626',
      backgroundColor: '#fef2f2',
    },
    penaltyHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 8,
    },
    penaltyEventTitle: {
      fontSize: isMobile ? 15 : 16,
      fontWeight: '600',
      color: colors.text,
      flex: 1,
      marginRight: 8,
    },
    penaltyStatusBadge: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 12,
      marginLeft: 8,
    },
    penaltyStatusText: {
      fontSize: isMobile ? 9 : 10,
      fontWeight: '600',
    },

    settingsSection: {
      paddingHorizontal: 20,
      paddingTop: 8,
    },
    settingsSectionTitle: {
      fontSize: isMobile ? 15 : 16,
      fontWeight: '600',
      marginBottom: 12,
      color: colors.text,
    },
    settingsOption: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    settingsOptionLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    settingsOptionText: {
      fontSize: isMobile ? 14 : 16,
      color: colors.text,
    },

    penaltyType: {
      fontSize: isMobile ? 12 : 13,
      color: colors.sidebar.text.secondary,
      marginBottom: 12,
      textTransform: 'capitalize',
    },
    penaltySection: {
      marginBottom: 12,
    },
    penaltyLabel: {
      fontSize: isMobile ? 11 : 12,
      fontWeight: '600',
      color: colors.sidebar.text.muted,
      marginBottom: 4,
      textTransform: 'uppercase',
    },
    penaltyConsequences: {
      fontSize: isMobile ? 13 : 14,
      color: colors.text,
      lineHeight: 20,
    },
    deadlineRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 12,
    },
    deadlineTextOverdue: {
      color: '#dc2626',
      fontWeight: '600',
    },
    statusRow: {
      flexDirection: 'row',
      marginBottom: 12,
    },
    statusBadge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    statusPending: {
      backgroundColor: '#fef3c7',
    },
    statusCompleted: {
      backgroundColor: '#d1fae5',
    },
    statusExcused: {
      backgroundColor: '#e0e7ff',
    },
    statusText: {
      fontSize: isMobile ? 10 : 11,
      fontWeight: '700',
    },
    penaltyActions: {
      flexDirection: 'row',
      gap: 10,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    penaltyActionBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
      borderRadius: 8,
      gap: 6,
      borderWidth: 1,
    },
    completeBtn: {
      borderColor: '#10b981',
      backgroundColor: '#ecfdf5',
    },
    completeBtnText: {
      color: '#10b981',
      fontWeight: '600',
      fontSize: isMobile ? 12 : 13,
    },
    excuseBtn: {
      borderColor: '#f59e0b',
      backgroundColor: '#fffbeb',
    },
    excuseBtnText: {
      color: '#f59e0b',
      fontWeight: '600',
      fontSize: isMobile ? 12 : 13,
    },
    emptyStateTitle: {
      fontSize: isMobile ? 16 : 18,
      fontWeight: 'bold',
      color: '#10b981',
      marginTop: 16,
      marginBottom: 8,
    },
    courseDisplayContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      padding: 40,
    },
    courseDisplayText: {
      fontSize: 42,
      fontWeight: 'bold',
      textAlign: 'center',
      paddingHorizontal: 20,
      paddingVertical: 10,
      backgroundColor: 'transparent',
    },

    summaryCard: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    summaryNumber: {
      fontSize: 24,
      fontWeight: 'bold',
    },
    summaryLabel: {
      fontSize: 12,
      marginTop: 4,
    },
    chartContainer: {
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    chartTitle: {
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 12,
    },
    chartSubtitle: {
      fontSize: 12,
      marginBottom: 16,
    },
    centerLabelValue: {
      fontSize: 24,
      fontWeight: 'bold',
    },
    centerLabelText: {
      fontSize: 12,
    },

    // Add these styles to your createProfileStyles function
    supportBanner: {
      borderRadius: 16,
      padding: 20,
      alignItems: 'center',
    },
    supportBannerTitle: {
      fontSize: 18,
      fontWeight: 'bold',
    },
    supportBannerText: {
      fontSize: 13,
      textAlign: 'center',
      lineHeight: 18,
    },
    contactSupportButton: {
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 25,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    supportCard: {
      borderRadius: 12,
      padding: 16,
      borderWidth: 1,
    },
    supportIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 12,
    },
    supportTitle: {
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 4,
    },
    supportDescription: {
      fontSize: 12,
    },
    faqItem: {
      borderRadius: 12,
      marginBottom: 8,
      borderWidth: 1,
      overflow: 'hidden',
    },
    faqQuestion: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
    },
    faqIconContainer: {
      width: 32,
      height: 32,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
    },
    faqQuestionText: {
      fontSize: 14,
      fontWeight: '600',
      flex: 1,
    },
    faqAnswer: {
      paddingHorizontal: 16,
      paddingBottom: 16,
      paddingTop: 0,
    },
    faqAnswerText: {
      fontSize: 13,
      lineHeight: 20,
    },
    reportProblemCard: {
      borderRadius: 16,
      padding: 20,
      borderWidth: 1,
    },
    reportTitle: {
      fontSize: 16,
      fontWeight: '600',
    },
    reportDescription: {
      fontSize: 13,
      lineHeight: 18,
    },
    reportButton: {
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 25,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      alignSelf: 'flex-start',
    },
    versionInfo: {
      alignItems: 'center',
      paddingVertical: 20,
    },

    copyrightText: {
      fontSize: 11,
      marginTop: 4,
    },

    pieLegendItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: 'transparent',
      backgroundColor: 'rgba(0,0,0,0.03)',
    },
    pieLegendDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
    },
    pieLegendText: {
      fontSize: isMobile ? 13 : 14,
    },
    pieLegendSubtext: {
      fontSize: isMobile ? 11 : 12,
      marginTop: 2,
    },
    sliceDetailsContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 16,
      padding: 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: 'rgba(0,0,0,0.1)',
    },
    sliceDetailsText: {
      fontSize: 13,
      fontWeight: '500',
    },
    // Header styles
    header: {
      paddingTop: isMobile ? 40 : 48,
      paddingBottom: isMobile ? 20 : 24,
      paddingHorizontal: isMobile ? 16 : 24,
      borderBottomLeftRadius: isMobile ? 24 : 32,
      borderBottomRightRadius: isMobile ? 24 : 32,
    },
    headerTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: isMobile ? 16 : 20,
    },
    greeting: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.muted,
      marginBottom: 2,
    },
    userName: {
      fontSize: isMobile ? 20 : 24,
      fontWeight: '700',
      color: '#ffffff',
      marginBottom: 2,
    },
    role: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.muted,
      fontWeight: '500',
    },
    profileButton: {
      width: isMobile ? 44 : 48,
      height: isMobile ? 44 : 48,
      borderRadius: isMobile ? 22 : 24,
      borderWidth: 2,
      borderColor: '#ffffff',
      overflow: 'hidden',
    },
    profileImage: {
      width: '100%',
      height: '100%',
    },
    profileFallback: {
      backgroundColor: colors.accent.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    profileInitials: {
      color: '#ffffff',
      fontSize: isMobile ? 16 : 18,
      fontWeight: '600',
    },
    headerBottom: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    dateContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: isMobile ? 8 : 10,
      paddingVertical: isMobile ? 4 : 6,
      marginTop: -20,
      marginLeft: -6,
    },
    dateText: {
      fontSize: isMobile ? 10 : 12,
      color: '#ffffff',
      fontWeight: '500',
    },
    logoutButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: 'rgba(239,68,68,0.15)',
      borderColor: 'rgba(239,68,68,0.3)',
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 20,
      marginTop: -20,
    },
    logoutButtonText: {
      color: '#ef4444',
      fontSize: isMobile ? 12 : 13,
      fontWeight: '600',
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 12,
      paddingTop: 12,
      paddingBottom: 24,
      gap: 12,
    },
    // Hero Card
    heroCard: {
      backgroundColor: colors.card,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    heroContent: {
      flexDirection: isMobile ? 'column' : 'row',
      alignItems: isMobile ? 'center' : 'flex-start',
      padding: 16,
      gap: 12,
    },
    avatarSection: {
      alignItems: 'center',
    },
    avatarButton: {
      width: 80,
      height: 80,
      borderRadius: 40,
      overflow: 'hidden',
      position: 'relative',
    },
    avatarImage: {
      width: '100%',
      height: '100%',
      borderRadius: 40,
    },
    avatarFallback: {
      width: '100%',
      height: '100%',
      backgroundColor: isDark ? 'rgba(14,165,233,0.2)' : '#e0f2fe',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 40,
      borderWidth: 2,
      borderColor: '#0ea5e9',
    },
    avatarInitials: {
      fontSize: 28,
      fontWeight: '800',
      color: '#0ea5e9',
    },
    avatarEditBadge: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: '#0ea5e9',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.card,
    },
    avatarLabel: {
      marginTop: 6,
      fontSize: 11,
      fontWeight: '600',
      color: colors.sidebar.text.secondary,
      textTransform: 'uppercase',
    },
    identitySection: {
      flex: 1,
      alignItems: isMobile ? 'center' : 'flex-start',
    },
    identityName: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.3,
      marginBottom: 2,
    },
    identityEmail: {
      fontSize: 13,
      color: colors.sidebar.text.secondary,
      marginBottom: 8,
    },
    memberSinceRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 4,
    },
    memberSinceText: {
      fontSize: 11,
      color: colors.sidebar.text.secondary,
    },
    courseInfo: {
      fontSize: 13,
      color: colors.sidebar.text.secondary,
      marginTop: 4,
    },
    statsGrid: {
      flexDirection: 'row',
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: isDark ? 'rgba(255,255,255,0.02)' : '#f8fafc',
    },
    statItem: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 12,
      borderRightWidth: 1,
      borderRightColor: colors.border,
    },
    statItemLast: {
      borderRightWidth: 0,
    },
    statIconBox: {
      width: 28,
      height: 28,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 4,
    },
    statValue: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.text,
    },
    statLabel: {
      fontSize: 10,
      fontWeight: '600',
      color: colors.sidebar.text.secondary,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    // Section Card
    sectionCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    sectionHeader: {
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    menuList: {
      paddingVertical: 4,
    },
    menuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    menuItemLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    menuItemText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
    },
    menuBadge: {
      backgroundColor: '#ef4444',
      width: 20,
      height: 20,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 8,
    },
    menuBadgeText: {
      color: '#ffffff',
      fontSize: 11,
      fontWeight: 'bold',
    },
    logoutCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? 'rgba(239,68,68,0.08)' : '#fef2f2',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(239,68,68,0.2)' : 'rgba(239,68,68,0.15)',
      paddingVertical: 14,
      gap: 10,
    },
    logoutText: {
      fontSize: 15,
      fontWeight: '700',
      color: '#ef4444',
    },
    footer: {
      alignItems: 'center',
      paddingVertical: 20,
      gap: 4,
    },
    footerText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
    },
    footerSub: {
      fontSize: 10,
      color: colors.sidebar.text.secondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    viewAllButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      marginTop: 8,
      backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
      borderRadius: 12,
    },
    viewAllButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.accent.primary,
      marginRight: 4,
    },
  })
}
