import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../context/ThemeContext';

export const createAnnouncementStyles = (
    colors: ThemeColors,
    isDark: boolean,
    isMobile: boolean,
    isTablet: boolean,
    isDesktop: boolean
) => {
    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: colors.background,
        },
        headerGradient: {
            paddingTop: isMobile ? 10 : 15,
            paddingBottom: isMobile ? 5 : 8,
            paddingHorizontal: isMobile ? 15 : 20,
        },
        headerContent: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: isMobile ? 15 : 20,
        },
        greetingText: {
            fontSize: isMobile ? 12 : 14,
            color: colors.sidebar.text.muted,
            marginBottom: 4,
        },
        userName: {
            fontSize: isMobile ? 20 : 24,
            fontWeight: '700',
            color: '#ffffff',
            marginBottom: 2,
        },
        roleText: {
            fontSize: isMobile ? 10 : 12,
            color: colors.sidebar.text.muted,
        },
        profileButton: {
            width: isMobile ? 40 : 50,
            height: isMobile ? 40 : 50,
            borderRadius: isMobile ? 20 : 25,
            borderWidth: 2,
            borderColor: '#ffffff',
            overflow: 'hidden',
        },
        profileImage: {
            width: '100%',
            height: '100%',
        },
        profileFallback: {
            backgroundColor: colors.accent.primary,
            justifyContent: 'center',
            alignItems: 'center',
        },
        profileInitials: {
            color: '#ffffff',
            fontSize: isMobile ? 16 : 18,
            fontWeight: '600',
        },
        dateSection: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginTop: isMobile ? -5 : 0,
        },
        dateContainer: {
            marginLeft: isMobile ? -5 : -10,
            marginTop: isMobile ? -15 : -20,
            flexDirection: 'row',
            alignItems: 'center',
            gap: 4,
            paddingHorizontal: isMobile ? 5 : 8,
            paddingVertical: isMobile ? 4 : 6,
        },
        dateText: {
            fontSize: isMobile ? 9 : 11,
            color: '#ffffff',
            fontWeight: '500',
        },
        headerActions: {
            flexDirection: 'row',
            gap: 12,
        },
        headerAction: {
            width: isMobile ? 36 : 40,
            height: isMobile ? 36 : 40,
            borderRadius: isMobile ? 18 : 20,
            backgroundColor: 'rgba(255, 255, 255, 0.18)',
            justifyContent: 'center',
            alignItems: 'center',
            position: 'relative',
        },
        notificationBadge: {
            position: 'absolute',
            top: 8,
            right: 8,
            backgroundColor: '#ef4444',
            borderRadius: 10,
            minWidth: 16,
            height: 16,
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 1,
            borderColor: '#ffffff',
        },
        notificationBadgeText: {
            color: '#ffffff',
            fontSize: 9,
            fontWeight: '700',
            paddingHorizontal: 3,
        },

        // Stats Grid
        statsGrid: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: isMobile ? 10 : 16,
            padding: isMobile ? 15 : 20,
            marginTop: isMobile ? -15 : -20,
        },
        statCard: {
            flex: 1,
            minWidth: isMobile ? '30%' : '22%',
            backgroundColor: colors.card,
            borderRadius: 20,
            padding: isMobile ? 12 : 16,
            borderWidth: 1,
            borderColor: colors.border,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: isDark ? 0.3 : 0.05,
            shadowRadius: 12,
            elevation: 3,
            borderLeftWidth: 4,
            borderLeftColor: colors.accent.primary,
            borderRightWidth: 4,
            borderRightColor: isDark ? colors.accent.primary : '#1266d4',
        },
        statIconContainer: {
            width: isMobile ? 36 : 44,
            height: isMobile ? 36 : 44,
            borderRadius: 12,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: `${colors.accent.primary}15`,
        },
        statNumber: {
            fontSize: isMobile ? 22 : 28,
            fontWeight: '800',
            color: colors.text,
            marginBottom: 4,
        },
        statLabel: {
            fontSize: isMobile ? 10 : 12,
            color: colors.sidebar.text.secondary,
            fontWeight: '500',
        },
        statSubtext: {
            fontSize: isMobile ? 10 : 11,
            color: colors.sidebar.text.muted,
            marginTop: 4,
        },

        // Main Content Grid
        mainContent: {
            flex: 1,
            flexDirection: isMobile ? 'column' : 'row',
            padding: isMobile ? 15 : 20,
            gap: 20,
        },
        leftGrid: {
            flex: isMobile ? undefined : 3,
            width: isMobile ? '100%' : undefined,
            backgroundColor: colors.card,
            borderRadius: 24,
            padding: 16,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: isDark ? 0.3 : 0.05,
            shadowRadius: 8,
            elevation: 2,
            borderWidth: 1,
            borderColor: colors.border,
            marginBottom: isMobile ? 15 : 0,
        },
        rightGrid: {
            flex: isMobile ? undefined : 3,
            width: isMobile ? '100%' : undefined,
            backgroundColor: colors.card,
            borderRadius: 24,
            padding: 16,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: isDark ? 0.3 : 0.05,
            shadowRadius: 8,
            elevation: 2,
            borderWidth: 1,
            borderColor: colors.border,
        },

        leftHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: isMobile ? 12 : 16,
            paddingHorizontal: 4,
        },
        leftTitle: {
            fontSize: isMobile ? 16 : 18,
            fontWeight: '700',
            color: colors.text,
        },
        leftControls: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: isMobile ? 8 : 12,
        },
        announcementCount: {
            fontSize: isMobile ? 12 : 14,
            color: colors.sidebar.text.secondary,
            backgroundColor: isDark ? colors.border : '#f1f5f9',
            paddingHorizontal: isMobile ? 8 : 10,
            paddingVertical: isMobile ? 3 : 4,
            borderRadius: 12,
            overflow: 'hidden',
        },
        leftFilters: {
            flexGrow: 0,
            marginRight: isMobile ? -15 : 0,
        },
        leftFilterButton: {
            paddingHorizontal: isMobile ? 10 : 12,
            paddingVertical: isMobile ? 5 : 6,
            borderRadius: 16,
            backgroundColor: isDark ? colors.border : '#f1f5f9',
            marginRight: isMobile ? 6 : 8,
        },
        leftFilterButtonActive: {
            backgroundColor: colors.accent.primary,
        },
        leftFilterButtonText: {
            fontSize: isMobile ? 11 : 12,
            color: colors.sidebar.text.secondary,
            fontWeight: '500',
        },
        leftFilterButtonTextActive: {
            color: '#ffffff',
        },

        // Paginated List
        paginatedList: {
            flex: 1,
        },
        paginatedItem: {
            flexDirection: 'row',
            alignItems: 'center',
            padding: isMobile ? 10 : 12,
            borderBottomWidth: 1,
            borderBottomColor: colors.border,
            gap: 12,
        },
        paginatedItemActive: {
            backgroundColor: isDark ? `${colors.accent.primary}20` : '#f0f9ff',
            borderLeftWidth: 3,
            borderLeftColor: colors.accent.primary,
        },
        paginatedNumber: {
            width: 28,
            height: 28,
            borderRadius: 8,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: `${colors.accent.primary}15`,
        },
        paginatedNumberText: {
            fontSize: 12,
            fontWeight: '600',
            color: colors.accent.primary,
        },
        paginatedInfo: {
            flex: 1,
        },
        paginatedTitle: {
            fontSize: isMobile ? 13 : 14,
            fontWeight: '600',
            color: colors.text,
            marginBottom: 4,
        },
        paginatedMeta: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
        },
        paginatedDate: {
            fontSize: isMobile ? 10 : 11,
            color: colors.sidebar.text.muted,
        },
        paginatedBadge: {
            paddingHorizontal: 6,
            paddingVertical: 2,
            borderRadius: 4,
        },
        paginatedBadgeText: {
            fontSize: 8,
            fontWeight: '700',
            color: '#ffffff',
            textTransform: 'uppercase',
        },
        paginatedCreator: {
            fontSize: isMobile ? 10 : 11,
            color: colors.sidebar.text.muted,
            marginTop: 2,
        },
        paginatedActions: {
            flexDirection: 'row',
            gap: 8,
        },
        paginatedEditButton: {
            width: isMobile ? 28 : 32,
            height: isMobile ? 28 : 32,
            borderRadius: 8,
            backgroundColor: isDark ? `${colors.accent.primary}20` : '#eff6ff',
            justifyContent: 'center',
            alignItems: 'center',
        },
        paginatedDeleteButton: {
            width: isMobile ? 28 : 32,
            height: isMobile ? 28 : 32,
            borderRadius: 8,
            backgroundColor: isDark ? '#ef444420' : '#fef2f2',
            justifyContent: 'center',
            alignItems: 'center',
        },
        paginationContainer: {
            flexDirection: 'row',
            justifyContent: 'center',
            alignItems: 'center',
            gap: isMobile ? 12 : 16,
            paddingTop: 16,
            marginTop: 16,
            borderTopWidth: 1,
            borderTopColor: colors.border,
        },
        paginationButton: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: isMobile ? 8 : 12,
            paddingVertical: isMobile ? 6 : 8,
            borderRadius: 20,
            backgroundColor: isDark ? colors.card : '#f8fafc',
            borderWidth: 1,
            borderColor: colors.border,
            gap: 4,
        },
        paginationButtonDisabled: {
            opacity: 0.5,
        },
        paginationButtonText: {
            fontSize: 12,
            fontWeight: '600',
            color: colors.accent.primary,
        },
        paginationButtonTextDisabled: {
            color: colors.sidebar.text.muted,
        },
        pageInfo: {
            alignItems: 'center',
        },
        pageInfoText: {
            fontSize: isMobile ? 12 : 14,
            fontWeight: '600',
            color: colors.text,
        },

        // Selected Detail View
        selectedDetailContainer: {
            marginTop: 16,
            padding: isMobile ? 12 : 16,
            backgroundColor: isDark ? colors.card : '#f8fafc',
            borderRadius: 16,
            borderWidth: 1,
            borderColor: colors.border,
        },
        selectedDetailHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: isMobile ? 8 : 12,
            paddingBottom: 8,
            borderBottomWidth: 1,
            borderBottomColor: colors.border,
        },
        selectedDetailTitle: {
            fontSize: isMobile ? 14 : 16,
            fontWeight: '700',
            color: colors.text,
        },
        selectedDetailContent: {
            gap: 12,
        },
        selectedDetailBadges: {
            flexDirection: 'row',
            gap: isMobile ? 6 : 8,
            marginBottom: 4,
        },
        detailBadge: {
            paddingHorizontal: isMobile ? 8 : 10,
            paddingVertical: isMobile ? 3 : 4,
            borderRadius: 6,
        },
        detailBadgeText: {
            fontSize: isMobile ? 9 : 10,
            fontWeight: '700',
            color: '#ffffff',
            textTransform: 'uppercase',
        },
        selectedDetailMessage: {
            fontSize: isMobile ? 13 : 14,
            color: colors.text,
            lineHeight: isMobile ? 18 : 20,
            marginBottom: isMobile ? 10 : 12,
        },
        selectedDetailFooter: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingTop: isMobile ? 10 : 12,
            borderTopWidth: 1,
            borderTopColor: colors.border,
        },
        selectedDetailDate: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: isMobile ? 4 : 6,
        },
        selectedDetailDateText: {
            fontSize: isMobile ? 10 : 12,
            color: colors.sidebar.text.muted,
        },
        selectedDetailCreator: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 4,
            marginTop: 4,
        },
        selectedDetailCreatorText: {
            fontSize: isMobile ? 11 : 13,
            color: colors.sidebar.text.muted,
        },
        selectedDetailActions: {
            flexDirection: 'row',
            gap: isMobile ? 8 : 12,
        },
        selectedDetailEditButton: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 6,
            paddingHorizontal: isMobile ? 10 : 12,
            paddingVertical: isMobile ? 5 : 6,
            backgroundColor: isDark ? `${colors.accent.primary}20` : '#eff6ff',
            borderRadius: 8,
        },
        selectedDetailEditText: {
            fontSize: isMobile ? 10 : 12,
            fontWeight: '600',
            color: colors.accent.primary,
        },
        selectedDetailDeleteButton: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 6,
            paddingHorizontal: isMobile ? 10 : 12,
            paddingVertical: isMobile ? 5 : 6,
            backgroundColor: isDark ? '#ef444420' : '#fef2f2',
            borderRadius: 8,
        },
        selectedDetailDeleteText: {
            fontSize: isMobile ? 10 : 12,
            fontWeight: '600',
            color: '#ef4444',
        },

        // Right side (search)
        rightHeader: {
            marginBottom: isMobile ? 15 : 20,
        },
        searchTitle: {
            fontSize: isMobile ? 16 : 18,
            fontWeight: '700',
            color: colors.text,
            marginBottom: 16,
        },
        searchContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: isDark ? colors.card : '#f8fafc',
            borderRadius: 16,
            paddingHorizontal: 16,
            paddingVertical: isMobile ? 10 : 12,
            borderWidth: 1,
            borderColor: colors.border,
            marginBottom: 16,
        },
        searchInput: {
            flex: 1,
            marginLeft: 12,
            fontSize: isMobile ? 13 : 14,
            color: colors.text,
        },
        searchClearButton: {
            padding: 4,
        },
        searchStats: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 16,
        },
        resultsCount: {
            fontSize: isMobile ? 13 : 14,
            color: colors.sidebar.text.secondary,
        },
        resultsHighlight: {
            fontSize: isMobile ? 13 : 14,
            color: colors.accent.primary,
            fontWeight: '600',
        },
        searchResultsContainer: {
            flex: 1,
        },
        searchResultItem: {
            backgroundColor: colors.card,
            borderRadius: 12,
            padding: isMobile ? 10 : 12,
            marginBottom: 8,
            borderWidth: 1,
            borderColor: colors.border,
        },
        searchResultHeader: {
            marginBottom: 8,
        },
        searchResultTitleContainer: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 0,
        },
        searchResultTitle: {
            fontSize: isMobile ? 13 : 14,
            fontWeight: '600',
            color: colors.text,
            flex: 1,
        },
        searchResultBadges: {
            flexDirection: 'row',
            gap: 4,
            marginLeft: 8,
        },
        searchResultBadge: {
            paddingHorizontal: 6,
            paddingVertical: 2,
            borderRadius: 4,
        },
        searchResultBadgeText: {
            fontSize: 8,
            fontWeight: '700',
            color: '#ffffff',
            textTransform: 'uppercase',
        },
        searchResultActions: {
            flexDirection: 'row',
            justifyContent: 'flex-end',
            gap: 8,
            marginTop: 4,
        },
        searchResultEditButton: {
            width: isMobile ? 26 : 28,
            height: isMobile ? 26 : 28,
            borderRadius: 6,
            backgroundColor: isDark ? `${colors.accent.primary}20` : '#eff6ff',
            justifyContent: 'center',
            alignItems: 'center',
        },
        searchResultDeleteButton: {
            width: isMobile ? 26 : 28,
            height: isMobile ? 26 : 28,
            borderRadius: 6,
            backgroundColor: isDark ? '#ef444420' : '#fef2f2',
            justifyContent: 'center',
            alignItems: 'center',
        },
        searchResultMessage: {
            fontSize: isMobile ? 12 : 13,
            color: colors.sidebar.text.secondary,
            lineHeight: isMobile ? 16 : 18,
            marginBottom: 8,
        },
        searchResultFooter: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            borderTopWidth: 1,
            borderTopColor: colors.border,
            paddingTop: 8,
        },
        searchResultDate: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 4,
        },
        searchResultDateText: {
            fontSize: isMobile ? 10 : 11,
            color: colors.sidebar.text.muted,
        },
        searchResultFullDate: {
            fontSize: isMobile ? 9 : 10,
            color: colors.sidebar.text.muted,
        },
        searchResultCreator: {
            fontSize: isMobile ? 10 : 11,
            color: colors.sidebar.text.muted,
            marginTop: 4,
        },

        // Empty / loading states
        emptyState: {
            alignItems: 'center',
            paddingVertical: isMobile ? 30 : 48,
        },
        emptyStateIcon: {
            width: isMobile ? 60 : 80,
            height: isMobile ? 60 : 80,
            borderRadius: isMobile ? 30 : 40,
            backgroundColor: colors.border,
            justifyContent: 'center',
            alignItems: 'center',
            marginBottom: 16,
        },
        emptyStateTitle: {
            fontSize: isMobile ? 16 : 18,
            fontWeight: '600',
            color: colors.sidebar.text.secondary,
            marginBottom: 8,
        },
        emptyStateText: {
            fontSize: isMobile ? 12 : 14,
            color: colors.sidebar.text.muted,
            textAlign: 'center',
            marginBottom: 24,
            maxWidth: 300,
        },
        loadingContainer: {
            padding: 24,
            alignItems: 'center',
            justifyContent: 'center',
        },
        loadingText: {
            marginTop: 8,
            fontSize: isMobile ? 11 : 12,
            color: colors.sidebar.text.secondary,
        },

        // Modal styles
        modernModalOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            justifyContent: 'center',
            alignItems: 'center',
        },
        modernModalContainer: {
            width: '90%',
            maxWidth: 500,
            backgroundColor: colors.card,
            borderRadius: 24,
            overflow: 'hidden',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 10 },
            shadowOpacity: 0.1,
            shadowRadius: 20,
            elevation: 10,
        },
        modernModalHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingHorizontal: isMobile ? 15 : 20,
            paddingVertical: isMobile ? 12 : 16,
            borderBottomWidth: 1,
            borderBottomColor: colors.border,
        },
        modernModalHeaderLeft: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: isMobile ? 8 : 12,
        },
        modernModalIconContainer: {
            width: isMobile ? 32 : 40,
            height: isMobile ? 32 : 40,
            borderRadius: 12,
            backgroundColor: `${colors.accent.primary}15`,
            justifyContent: 'center',
            alignItems: 'center',
        },
        modernModalTitleContainer: {
            gap: 2,
        },
        modernModalTitle: {
            fontSize: isMobile ? 16 : 18,
            fontWeight: '700',
            color: colors.text,
        },
        modernModalSubtitle: {
            fontSize: isMobile ? 10 : 12,
            color: colors.sidebar.text.secondary,
        },
        modernModalCloseButton: {
            width: isMobile ? 32 : 36,
            height: isMobile ? 32 : 36,
            borderRadius: isMobile ? 16 : 18,
            backgroundColor: colors.border,
            justifyContent: 'center',
            alignItems: 'center',
        },
        modernModalContent: {
            padding: isMobile ? 15 : 20,
        },
        modernFormGroup: {
            marginBottom: 20,
        },
        modernFormLabel: {
            fontSize: isMobile ? 13 : 14,
            fontWeight: '600',
            color: colors.text,
            marginBottom: 8,
            marginLeft: 4,
        },
        modernFormInput: {
            backgroundColor: isDark ? colors.card : '#f8fafc',
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: 16,
            paddingHorizontal: 16,
            paddingVertical: isMobile ? 12 : 14,
            fontSize: isMobile ? 13 : 14,
            color: colors.text,
        },
        modernTextArea: {
            height: isMobile ? 100 : 120,
            textAlignVertical: 'top',
        },
        modernFormActions: {
            flexDirection: 'row',
            gap: 12,
            marginTop: 24,
        },
        modernSubmitButton: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            backgroundColor: colors.accent.primary,
            paddingVertical: isMobile ? 12 : 14,
            borderRadius: 16,
        },
        modernSubmitButtonDisabled: {
            backgroundColor: colors.sidebar.text.muted,
        },
        modernSubmitButtonText: {
            color: '#ffffff',
            fontSize: isMobile ? 14 : 16,
            fontWeight: '600',
        },
        modernCancelButton: {
            flex: 1,
            backgroundColor: colors.border,
            paddingVertical: isMobile ? 12 : 14,
            borderRadius: 16,
            alignItems: 'center',
        },
        modernCancelButtonText: {
            color: colors.sidebar.text.secondary,
            fontSize: isMobile ? 14 : 16,
            fontWeight: '600',
        },

        // Priority selector
        priorityContainer: {
            flexDirection: 'row',
            gap: isMobile ? 6 : 10,
            marginBottom: 8,
        },
        priorityButton: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: isMobile ? 6 : 8,
            paddingVertical: isMobile ? 10 : 12,
            paddingHorizontal: isMobile ? 6 : 8,
            borderRadius: 12,
            backgroundColor: isDark ? colors.card : '#f8fafc',
            borderWidth: 1,
            borderColor: colors.border,
        },
        priorityButtonNormalActive: {
            backgroundColor: `${colors.accent.primary}15`,
            borderColor: colors.accent.primary,
        },
        priorityButtonImportantActive: {
            backgroundColor: '#f59e0b15',
            borderColor: '#f59e0b',
        },
        priorityButtonUrgentActive: {
            backgroundColor: '#ef444415',
            borderColor: '#ef4444',
        },
        priorityIndicator: {
            width: isMobile ? 10 : 12,
            height: isMobile ? 10 : 12,
            borderRadius: isMobile ? 5 : 6,
        },
        priorityButtonText: {
            fontSize: isMobile ? 12 : 13,
            fontWeight: '500',
            color: colors.sidebar.text.secondary,
        },
        priorityButtonTextActive: {
            color: colors.text,
            fontWeight: '600',
        },
        priorityHint: {
            fontSize: isMobile ? 11 : 12,
            color: colors.sidebar.text.muted,
            marginTop: 4,
            marginLeft: 4,
            fontStyle: 'italic',
        },

        // Additional mobile-specific styles
        headerGradientMobile: { paddingTop: 10, paddingBottom: 5, paddingHorizontal: 15 },
        headerContentMobile: { marginBottom: 15 },
        greetingTextMobile: { fontSize: 12 },
        userNameMobile: { fontSize: 20 },
        roleTextMobile: { fontSize: 10 },
        profileButtonMobile: { width: 40, height: 40, borderRadius: 20 },
        profileInitialsMobile: { fontSize: 16 },
        dateSectionMobile: { marginTop: -5 },
        dateContainerMobile: { marginLeft: -5, marginTop: -15, paddingHorizontal: 5, paddingVertical: 4 },
        dateTextMobile: { fontSize: 9 },
        headerActionMobile: { width: 36, height: 36, borderRadius: 18 },
        statsGridMobile: { gap: 10, padding: 15, marginTop: -15 },
        statCardMobile: { padding: 12, minWidth: '30%' },
        statIconContainerMobile: { width: 36, height: 36, borderRadius: 10 },
        statNumberMobile: { fontSize: 22 },
        statLabelMobile: { fontSize: 10 },
        mainContentMobile: { flexDirection: 'column', padding: 15, gap: 15 },
        leftGridMobile: { flex: undefined, width: '100%', marginBottom: 15 },
        rightGridMobile: { flex: undefined, width: '100%' },
        leftHeaderMobile: { marginBottom: 12 },
        leftTitleMobile: { fontSize: 16 },
        leftControlsMobile: { gap: 8 },
        announcementCountMobile: { fontSize: 12, paddingHorizontal: 8, paddingVertical: 3 },
        leftFiltersMobile: { marginRight: -15 },
        leftFilterButtonMobile: { paddingHorizontal: 10, paddingVertical: 5, marginRight: 6 },
        leftFilterButtonTextMobile: { fontSize: 11 },
        paginatedItemMobile: { padding: 10, gap: 8 },
        paginatedTitleMobile: { fontSize: 13 },
        paginatedDateMobile: { fontSize: 10 },
        paginatedCreatorMobile: { fontSize: 10 },
        paginatedEditButtonMobile: { width: 28, height: 28, borderRadius: 6 },
        paginatedDeleteButtonMobile: { width: 28, height: 28, borderRadius: 6 },
        paginationContainerMobile: { gap: 12, paddingTop: 12, marginTop: 12 },
        paginationButtonMobile: { paddingHorizontal: 8, paddingVertical: 6 },
        pageInfoTextMobile: { fontSize: 12 },
        selectedDetailContainerMobile: { marginTop: 12, padding: 12 },
        selectedDetailHeaderMobile: { marginBottom: 8, paddingBottom: 6 },
        selectedDetailTitleMobile: { fontSize: 14 },
        selectedDetailBadgesMobile: { gap: 6 },
        detailBadgeMobile: { paddingHorizontal: 8, paddingVertical: 3 },
        detailBadgeTextMobile: { fontSize: 9 },
        selectedDetailMessageMobile: { fontSize: 13, lineHeight: 18, marginBottom: 10 },
        selectedDetailFooterMobile: { paddingTop: 10 },
        selectedDetailDateMobile: { gap: 4 },
        selectedDetailDateTextMobile: { fontSize: 10 },
        selectedDetailActionsMobile: { gap: 8 },
        selectedDetailEditButtonMobile: { paddingHorizontal: 10, paddingVertical: 5 },
        selectedDetailDeleteButtonMobile: { paddingHorizontal: 10, paddingVertical: 5 },
        rightHeaderMobile: { marginBottom: 15 },
        searchTitleMobile: { fontSize: 16, marginBottom: 12 },
        searchContainerMobile: { paddingHorizontal: 12, paddingVertical: 10, marginBottom: 12 },
        searchInputMobile: { marginLeft: 8, fontSize: 13 },
        searchStatsMobile: { marginBottom: 12 },
        resultsCountMobile: { fontSize: 13 },
        searchResultItemMobile: { padding: 10, marginBottom: 6 },
        searchResultTitleMobile: { fontSize: 13 },
        searchResultEditButtonMobile: { width: 26, height: 26, borderRadius: 5 },
        searchResultDeleteButtonMobile: { width: 26, height: 26, borderRadius: 5 },
        searchResultMessageMobile: { fontSize: 12, lineHeight: 16, marginBottom: 6 },
        searchResultDateTextMobile: { fontSize: 10 },
        searchResultFullDateMobile: { fontSize: 9 },
        searchResultCreatorMobile: { fontSize: 10 },
        emptyStateMobile: { paddingVertical: 30 },
        emptyStateIconMobile: { width: 60, height: 60, borderRadius: 30, marginBottom: 12 },
        emptyStateTitleMobile: { fontSize: 16 },
        emptyStateTextMobile: { fontSize: 12, maxWidth: 250 },
        loadingTextMobile: { fontSize: 11 },
        modernModalContainerMobile: { width: '95%', maxWidth: 400 },
        modernModalHeaderMobile: { paddingHorizontal: 15, paddingVertical: 12 },
        modernModalHeaderLeftMobile: { gap: 8 },
        modernModalIconContainerMobile: { width: 32, height: 32, borderRadius: 10 },
        modernModalTitleMobile: { fontSize: 16 },
        modernModalSubtitleMobile: { fontSize: 10 },
        modernModalCloseButtonMobile: { width: 32, height: 32, borderRadius: 16 },
        modernModalContentMobile: { padding: 15 },
        modernFormLabelMobile: { fontSize: 13, marginBottom: 6 },
        modernFormInputMobile: { paddingHorizontal: 14, paddingVertical: 12, fontSize: 13 },
        priorityContainerMobile: { gap: 6 },
        priorityButtonMobile: { paddingVertical: 10, paddingHorizontal: 6, gap: 6 },
        priorityIndicatorMobile: { width: 10, height: 10, borderRadius: 5 },
        priorityButtonTextMobile: { fontSize: 12 },
        modernFormActionsMobile: { gap: 8, marginTop: 20 },
        modernSubmitButtonMobile: { paddingVertical: 12 },
        modernSubmitButtonTextMobile: { fontSize: 14 },
        modernCancelButtonMobile: { paddingVertical: 12 },
        modernCancelButtonTextMobile: { fontSize: 14 },
        selectedDetailCreatorMobile: { marginTop: 2 },
        selectedDetailCreatorTextMobile: { fontSize: 11 },
        paginatedBadgeContainer: {
            flexDirection: 'row',
            gap: 4,
            marginLeft: 8,
        },
        paginatedTitleRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: 4,
        },
    });
};