import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../context/ThemeContext';

export const createEventsStyles = (
    colors: ThemeColors,
    isDark: boolean,
    isMobile: boolean,
    isTablet: boolean,
    isDesktop: boolean,
    screenHeight: number
) => {

    const getStatusBg = (status?: string) => {
        switch (status) {
            case 'pending': return '#f59e0b';
            case 'approved': return '#10b981';
            case 'rejected': return '#ef4444';
            default: return colors.accent.primary;
        }
    };

    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: colors.background,
        },
        headerGradient: {
            paddingTop: isMobile ? 15 : 20,
            paddingBottom: isMobile ? 8 : 12,
            paddingHorizontal: isMobile ? 16 : 24,
        },
        headerContent: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: isMobile ? 12 : 16,
        },
        greetingText: {
            fontSize: isMobile ? 11 : 13,
            fontWeight: '500',
            letterSpacing: 0.3,
            color: colors.sidebar.text.muted,
            opacity: 0.75,
            marginBottom: 2,
        },
        userName: {
            fontSize: isMobile ? 20 : 26,
            fontWeight: '800',
            letterSpacing: -0.8,
            color: '#ffffff',
            marginBottom: 2,
        },
        roleText: {
            fontSize: isMobile ? 10 : 12,
            fontWeight: '500',
            letterSpacing: 0.8,
            textTransform: 'uppercase',
            color: colors.sidebar.text.muted,
            opacity: 0.6,
            marginLeft: -4,
        },
        profileButton: {
            width: 48,
            height: 48,
            borderRadius: 24,
            borderWidth: 2.5,
            borderColor: 'rgba(255,255,255,0.7)',
            overflow: 'hidden',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.25,
            shadowRadius: 8,
            elevation: 6,
        },
        characterCounterContainer: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginTop: 8,
        },
        characterCounterText: {
            fontSize: 12,
        },
        characterCounterWarning: {
            fontSize: 12,
            color: '#ef4444',
        },
        profileImage: {
            width: '100%',
            height: '100%',
        },
        profileFallback: {
            backgroundColor: 'rgba(255,255,255,0.2)',
            justifyContent: 'center',
            alignItems: 'center',
        },
        profileInitials: {
            color: '#ffffff',
            fontSize: isMobile ? 16 : 18,
            fontWeight: '600',
        },
        dateSection: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginTop: 0,
        },
        dateContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 4,
            paddingHorizontal: isMobile ? 6 : 8,
            paddingVertical: isMobile ? 4 : 6,
            marginLeft: 0,
            marginTop: 0,
        },
        dateText: {
            fontSize: isMobile ? 10 : 12,
            fontWeight: '500',
            letterSpacing: 0.2,
            color: '#ffffff',
            marginLeft: -8,
        },
        headerActions: {
            flexDirection: 'row',
            gap: 12,
        },
        modernFormInputMobile: {
            paddingHorizontal: 14,
            paddingVertical: 12,
            fontSize: 13,
        },
        headerAction: {
            width: isMobile ? 36 : 40,
            height: isMobile ? 36 : 40,
            borderRadius: isMobile ? 18 : 20,
            backgroundColor: 'rgba(255, 255, 255, 0.18)',
            justifyContent: 'center',
            alignItems: 'center',
            position: 'relative',
        },
        notificationBadge: {
            position: 'absolute',
            top: 8,
            right: 8,
            backgroundColor: '#ef4444',
            borderRadius: 10,
            minWidth: 16,
            height: 16,
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 1,
            borderColor: '#ffffff',
        },
        notificationBadgeText: {
            color: '#ffffff',
            fontSize: 9,
            fontWeight: '700',
            paddingHorizontal: 3,
        },

        // Main Content Grid
        mainContent: {
            flex: 1,
            flexDirection: isMobile ? 'column' : 'row',
            padding: isMobile ? 15 : 20,
            gap: 20,
        },
        leftGrid: {
            flex: isMobile ? undefined : 3,
            width: isMobile ? '100%' : undefined,
            backgroundColor: colors.card,
            borderRadius: 24,
            padding: 16,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: isDark ? 0.3 : 0.05,
            shadowRadius: 8,
            elevation: 2,
            borderWidth: 1,
            borderColor: colors.border,
            marginBottom: isMobile ? 15 : 0,
        },
        rightGrid: {
            flex: isMobile ? undefined : 3,
            width: isMobile ? '100%' : undefined,
            backgroundColor: colors.card,
            borderRadius: 24,
            padding: 16,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: isDark ? 0.3 : 0.05,
            shadowRadius: 8,
            elevation: 2,
            borderWidth: 1,
            borderColor: colors.border,
        },

        leftHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: isMobile ? 12 : 16,
            paddingHorizontal: 4,
        },
        leftTitle: {
            fontSize: isMobile ? 16 : 18,
            fontWeight: '700',
            color: colors.text,
        },
        leftControls: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: isMobile ? 8 : 12,
        },
        eventCount: {
            fontSize: isMobile ? 12 : 14,
            color: colors.sidebar.text.secondary,
            backgroundColor: isDark ? colors.border : '#f1f5f9',
            paddingHorizontal: isMobile ? 8 : 10,
            paddingVertical: isMobile ? 3 : 4,
            borderRadius: 12,
            overflow: 'hidden',
        },
        leftFilters: {
            flexGrow: 0,
            marginRight: isMobile ? -15 : 0,
        },
        leftFilterButton: {
            paddingHorizontal: isMobile ? 10 : 12,
            paddingVertical: isMobile ? 5 : 6,
            borderRadius: 16,
            backgroundColor: isDark ? colors.border : '#f1f5f9',
            marginRight: isMobile ? 6 : 8,
        },
        leftFilterButtonActive: {
            backgroundColor: colors.accent.primary,
        },
        leftFilterButtonText: {
            fontSize: isMobile ? 11 : 12,
            color: colors.sidebar.text.secondary,
            fontWeight: '500',
        },
        leftFilterButtonTextActive: {
            color: '#ffffff',
        },

        // Paginated List
        paginatedList: {
            flex: 1,
        },
        paginatedItem: {
            flexDirection: 'row',
            alignItems: 'center',
            padding: isMobile ? 10 : 12,
            borderBottomWidth: 1,
            borderBottomColor: colors.border,
            gap: 12,
        },
        paginatedItemActive: {
            backgroundColor: isDark ? `${colors.accent.primary}20` : '#f0f9ff',
            borderLeftWidth: 3,
            borderLeftColor: colors.accent.primary,
        },
        paginatedNumber: {
            width: 28,
            height: 28,
            borderRadius: 8,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: `${colors.accent.primary}15`,
        },
        paginatedNumberText: {
            fontSize: 12,
            fontWeight: '600',
            color: colors.accent.primary,
        },
        paginatedInfo: {
            flex: 1,
        },
        paginatedTitle: {
            fontSize: isMobile ? 13 : 14,
            fontWeight: '600',
            color: colors.text,
            marginBottom: 4,
        },
        paginatedMeta: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
        },
        paginatedDate: {
            fontSize: isMobile ? 10 : 11,
            color: colors.sidebar.text.muted,
        },
        paginatedBadge: {
            paddingHorizontal: 6,
            paddingVertical: 2,
            borderRadius: 4,
        },
        paginatedBadgeText: {
            fontSize: 8,
            fontWeight: '700',
            color: '#ffffff',
            textTransform: 'uppercase',
        },
        eventBadgeText: {
            fontSize: 8,
            fontWeight: '700',
            color: '#ffffff',
            textTransform: 'uppercase',
        },
        paginatedLocation: {
            fontSize: 10,
            color: colors.accent.primary,
            marginLeft: 4,
        },
        paginatedActions: {
            flexDirection: 'row',
            gap: 8,
        },
        paginatedEditButton: {
            width: isMobile ? 28 : 32,
            height: isMobile ? 28 : 32,
            borderRadius: 8,
            backgroundColor: isDark ? `${colors.accent.primary}20` : '#eff6ff',
            justifyContent: 'center',
            alignItems: 'center',
        },
        paginatedDeleteButton: {
            width: isMobile ? 28 : 32,
            height: isMobile ? 28 : 32,
            borderRadius: 8,
            backgroundColor: isDark ? '#ef444420' : '#fef2f2',
            justifyContent: 'center',
            alignItems: 'center',
        },
        paginationContainer: {
            flexDirection: 'row',
            justifyContent: 'center',
            alignItems: 'center',
            gap: isMobile ? 12 : 16,
            paddingTop: 16,
            marginTop: 16,
            borderTopWidth: 1,
            borderTopColor: colors.border,
        },
        paginationButton: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: isMobile ? 8 : 12,
            paddingVertical: isMobile ? 6 : 8,
            borderRadius: 20,
            backgroundColor: isDark ? colors.card : '#f8fafc',
            borderWidth: 1,
            borderColor: colors.border,
            gap: 4,
        },
        paginationButtonDisabled: {
            opacity: 0.5,
        },
        paginationButtonText: {
            fontSize: 12,
            fontWeight: '600',
            color: colors.accent.primary,
        },
        paginationButtonTextDisabled: {
            color: colors.sidebar.text.muted,
        },
        pageInfo: {
            alignItems: 'center',
        },
        pageInfoText: {
            fontSize: isMobile ? 12 : 14,
            fontWeight: '600',
            color: colors.text,
        },

        // Right side (search)
        rightHeader: {
            marginBottom: 20,
        },
        searchTitle: {
            fontSize: isMobile ? 16 : 18,
            fontWeight: '700',
            color: colors.text,
            marginBottom: 16,
        },
        searchContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: isDark ? colors.card : '#f8fafc',
            borderRadius: 16,
            paddingHorizontal: 16,
            paddingVertical: isMobile ? 10 : 12,
            borderWidth: 1,
            borderColor: colors.border,
            marginBottom: 16,
        },
        searchInput: {
            flex: 1,
            marginLeft: 12,
            fontSize: isMobile ? 13 : 14,
            color: colors.text,
        },
        searchClearButton: {
            padding: 4,
        },
        searchStats: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 16,
        },
        resultsCount: {
            fontSize: isMobile ? 13 : 14,
            color: colors.sidebar.text.secondary,
        },
        resultsHighlight: {
            fontSize: isMobile ? 13 : 14,
            color: colors.accent.primary,
            fontWeight: '600',
        },
        searchResultsContainer: {
            flex: 1,
        },
        searchResultItem: {
            backgroundColor: colors.card,
            borderRadius: 12,
            padding: isMobile ? 10 : 12,
            marginBottom: 8,
            borderWidth: 1,
            borderColor: colors.border,
        },
        searchResultHeader: {
            marginBottom: 8,
        },
        searchResultTitleContainer: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 4,
        },
        searchResultTitle: {
            fontSize: isMobile ? 13 : 14,
            fontWeight: '600',
            color: colors.text,
            flex: 1,
        },
        searchResultBadges: {
            flexDirection: 'row',
            gap: 4,
            marginLeft: 8,
        },
        searchResultBadge: {
            paddingHorizontal: 6,
            paddingVertical: 2,
            borderRadius: 4,
        },
        searchResultBadgeText: {
            fontSize: 8,
            fontWeight: '700',
            color: '#ffffff',
            textTransform: 'uppercase',
        },
        searchResultLocation: {
            fontSize: isMobile ? 10 : 11,
            color: colors.accent.primary,
            marginBottom: 4,
            flexDirection: 'row',
            alignItems: 'center',
        },
        searchResultActions: {
            flexDirection: 'row',
            justifyContent: 'flex-end',
            gap: 8,
            marginTop: 4,
        },
        searchResultEditButton: {
            width: isMobile ? 26 : 28,
            height: isMobile ? 26 : 28,
            borderRadius: 6,
            backgroundColor: isDark ? `${colors.accent.primary}20` : '#eff6ff',
            justifyContent: 'center',
            alignItems: 'center',
        },
        searchResultDeleteButton: {
            width: isMobile ? 26 : 28,
            height: isMobile ? 26 : 28,
            borderRadius: 6,
            backgroundColor: isDark ? '#ef444420' : '#fef2f2',
            justifyContent: 'center',
            alignItems: 'center',
        },
        searchResultDescription: {
            fontSize: isMobile ? 12 : 13,
            color: colors.sidebar.text.secondary,
            lineHeight: 18,
            marginBottom: 8,
        },
        searchResultFooter: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            borderTopWidth: 1,
            borderTopColor: colors.border,
            paddingTop: 8,
        },
        searchResultDate: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 4,
        },
        searchResultDateText: {
            fontSize: isMobile ? 10 : 11,
            color: colors.sidebar.text.muted,
        },
        searchResultAttendees: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 4,
        },
        searchResultAttendeesText: {
            fontSize: isMobile ? 9 : 10,
            color: colors.sidebar.text.muted,
        },


        emptyState: {
            alignItems: 'center',
            paddingVertical: isMobile ? 30 : 48,
        },
        emptyStateIcon: {
            width: isMobile ? 60 : 80,
            height: isMobile ? 60 : 80,
            borderRadius: isMobile ? 30 : 40,
            backgroundColor: colors.border,
            justifyContent: 'center',
            alignItems: 'center',
            marginBottom: 16,
        },
        emptyStateTitle: {
            fontSize: isMobile ? 16 : 18,
            fontWeight: '600',
            color: colors.sidebar.text.secondary,
            marginBottom: 8,
        },
        emptyStateText: {
            fontSize: isMobile ? 12 : 14,
            color: colors.sidebar.text.muted,
            textAlign: 'center',
            marginBottom: 24,
            maxWidth: 300,
        },

        loadingContainer: {
            padding: 24,
            alignItems: 'center',
            justifyContent: 'center',
        },
        loadingText: {
            marginTop: 8,
            fontSize: isMobile ? 11 : 12,
            color: colors.sidebar.text.secondary,
        },
        resultsInfo: {
            paddingHorizontal: isMobile ? 12 : 16,
            marginTop: 8,
            marginBottom: 12,
        },
        resultsText: {
            fontSize: isMobile ? 11 : 13,
            color: colors.sidebar.text.secondary,
        },

        // Modal styles
        modernModalOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            justifyContent: 'center',
            alignItems: 'center',
        },
        modernModalContainer: {
            width: '90%',
            maxWidth: 500,
            backgroundColor: colors.card,
            borderRadius: 24,
            overflow: 'hidden',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 10 },
            shadowOpacity: 0.1,
            shadowRadius: 20,
            elevation: 10,
        },
        modernModalHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingHorizontal: isMobile ? 15 : 20,
            paddingVertical: isMobile ? 12 : 16,
            borderBottomWidth: 1,
            borderBottomColor: colors.border,
        },
        modernModalHeaderLeft: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: isMobile ? 8 : 12,
        },
        modernModalIconContainer: {
            width: isMobile ? 32 : 40,
            height: isMobile ? 32 : 40,
            borderRadius: 12,
            backgroundColor: `${colors.accent.primary}15`,
            justifyContent: 'center',
            alignItems: 'center',
        },
        modernModalTitleContainer: {
            gap: 2,
        },
        modernModalTitle: {
            fontSize: isMobile ? 16 : 18,
            fontWeight: '700',
            color: colors.text,
        },
        modernModalSubtitle: {
            fontSize: isMobile ? 10 : 12,
            color: colors.sidebar.text.secondary,
        },
        modernModalCloseButton: {
            width: isMobile ? 32 : 36,
            height: isMobile ? 32 : 36,
            borderRadius: isMobile ? 16 : 18,
            backgroundColor: colors.border,
            justifyContent: 'center',
            alignItems: 'center',
        },
        modernModalContent: {
            padding: isMobile ? 15 : 20,
            maxHeight: 600,
        },
        modernFormGroup: {
            marginBottom: 20,
        },
        modernFormLabel: {
            fontSize: isMobile ? 13 : 14,
            fontWeight: '600',
            color: colors.text,
            marginBottom: 8,
            marginLeft: 4,
        },
        modernFormInput: {
            backgroundColor: isDark ? colors.card : '#f8fafc',
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: 16,
            paddingHorizontal: 16,
            paddingVertical: isMobile ? 12 : 14,
            fontSize: isMobile ? 13 : 14,
            color: colors.text,
        },
        modernTextArea: {
            height: 100,
            textAlignVertical: 'top',
        },
        modernLocationButton: {
            backgroundColor: isDark ? colors.card : '#f8fafc',
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: 16,
            padding: 16,
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
        },
        modernLocationButtonText: {
            flex: 1,
        },
        modernLocationButtonTitle: {
            fontSize: 14,
            fontWeight: '600',
            color: colors.text,
            marginBottom: 4,
        },
        modernLocationButtonSubtitle: {
            fontSize: 12,
            color: colors.sidebar.text.muted,
        },
        modernCoordinatesButton: {
            backgroundColor: isDark ? colors.card : '#f8fafc',
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: 16,
            padding: 16,
            marginTop: 12,
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
        },
        modernFormActions: {
            flexDirection: 'row',
            gap: 12,
            marginTop: 24,
        },
        modernSubmitButton: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            backgroundColor: colors.accent.primary,
            paddingVertical: isMobile ? 12 : 14,
            borderRadius: 16,
        },
        modernSubmitButtonDisabled: {
            backgroundColor: colors.sidebar.text.muted,
        },
        modernSubmitButtonText: {
            color: '#ffffff',
            fontSize: isMobile ? 14 : 16,
            fontWeight: '600',
        },
        modernCancelButton: {
            flex: 1,
            backgroundColor: colors.border,
            paddingVertical: isMobile ? 12 : 14,
            borderRadius: 16,
            alignItems: 'center',
        },
        modernCancelButtonText: {
            color: colors.sidebar.text.secondary,
            fontSize: isMobile ? 14 : 16,
            fontWeight: '600',
        },

        // Detail view inside modal
        modernDetailImageContainer: {
            width: '100%',
            height: isMobile ? 100 : 120,
            borderRadius: 12,
            overflow: 'hidden',
            marginBottom: 16,
            position: 'relative',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.1,
            shadowRadius: 8,
            elevation: 4,
        },
        modernDetailImage: {
            width: '100%',
            height: '100%',
        },
        modernDetailImageBadge: {
            position: 'absolute',
            top: 8,
            right: 8,
            paddingHorizontal: 10,
            paddingVertical: 4,
            borderRadius: 6,
            backgroundColor: colors.accent.primary,
        },
        modernDetailTitle: {
            fontSize: isMobile ? 16 : 18,
            fontWeight: '700',
            color: colors.text,
            marginBottom: 16,
        },
        modernDetailSection: {
            marginBottom: 16,
        },
        modernDetailLabel: {
            fontSize: 12,
            fontWeight: '600',
            color: colors.sidebar.text.secondary,
            marginBottom: 6,
            textTransform: 'uppercase',
            letterSpacing: 0.5,
        },
        modernDetailText: {
            fontSize: isMobile ? 13 : 14,
            color: colors.text,
            lineHeight: 20,
            backgroundColor: isDark ? colors.card : '#f8fafc',
            padding: isMobile ? 10 : 12,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: colors.border,
        },
        modernDetailRow: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
            marginBottom: 12,
            paddingVertical: 4,
            flexWrap: 'wrap',
        },
        modernDetailRowText: {
            fontSize: 14,
            color: colors.sidebar.text.secondary,
            flex: 1,
        },
        modernDetailIconButton: {
            width: 32,
            height: 32,
            borderRadius: 16,
            backgroundColor: `${colors.accent.primary}20`,
            justifyContent: 'center',
            alignItems: 'center',
            marginLeft: 8,
        },
        modernDetailRangeHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 8,
        },
        rangeIndicator: {
            paddingHorizontal: 8,
            paddingVertical: 4,
            borderRadius: 4,
        },
        rangeIndicatorText: {
            fontSize: 10,
            fontWeight: '600',
            color: '#ffffff',
            textTransform: 'uppercase',
        },
        rangeVisualization: {
            marginTop: 8,
            marginBottom: 16,
        },
        rangeTrack: {
            height: 8,
            backgroundColor: colors.border,
            borderRadius: 4,
            overflow: 'hidden',
            marginBottom: 4,
        },
        rangeFill: {
            height: '100%',
            backgroundColor: colors.accent.primary,
            borderRadius: 4,
        },
        rangeTrackText: {
            fontSize: 11,
            color: colors.sidebar.text.muted,
            textAlign: 'center',
        },
        checkLocationButton: {
            backgroundColor: colors.accent.primary,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            paddingVertical: 10,
            paddingHorizontal: 16,
            borderRadius: 12,
            marginTop: 8,
        },
        checkLocationButtonDisabled: {
            backgroundColor: colors.sidebar.text.muted,
        },
        checkLocationButtonText: {
            color: '#ffffff',
            fontSize: 13,
            fontWeight: '500',
        },
        // ────── Glassmorphism Modal Styles 
        glassModalOverlay: {
            flex: 1,
            backgroundColor: isDark ? 'rgba(15, 23, 42, 0.78)' : 'rgba(15, 23, 42, 0.65)',
            justifyContent: 'center',
            alignItems: 'center',
            padding: isMobile ? 16 : 24,
        },
        glassModalContent: {
            width: '100%',
            maxWidth: 560,
            backgroundColor: isDark
                ? 'rgba(255, 255, 255, 0.09)'
                : 'rgba(255, 255, 255, 0.88)',
            borderWidth: 1,
            borderColor: isDark
                ? 'rgba(255, 255, 255, 0.18)'
                : 'rgba(255, 255, 255, 0.65)',
            borderRadius: 28,
            overflow: 'hidden',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 25 },
            shadowOpacity: isDark ? 0.45 : 0.18,
            shadowRadius: 35,
            elevation: 25,
        },
        glassModalContentMobile: {
            maxWidth: '100%',
            borderRadius: 24,
        },
        glassModalHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingHorizontal: isMobile ? 20 : 24,
            paddingVertical: 20,
            borderBottomWidth: 1,
            borderBottomColor: isDark ? 'rgba(255,255,255,0.12)' : 'rgba(0,0,0,0.08)',
        },
        glassModalTitle: {
            fontSize: isDesktop ? 21 : 19,
            fontWeight: '700',
            color: colors.text,
        },
        glassModalTitleMobile: {
            fontSize: 18,
        },
        glassModalClose: {
            padding: 6,
        },
        glassModalBody: {
            padding: isMobile ? 20 : 28,
            maxHeight: isMobile ? screenHeight * 0.85 : 620,
        },
        glassModalBodyMobile: {
            padding: 18,
        },

        searchResultItemActive: {
            backgroundColor: isDark ? '#1e293b' : '#f1f5f9',
            borderColor: '#0ea5e9',
            borderWidth: 1.5,
            shadowColor: '#0ea5e9',
            shadowOpacity: 0.15,
            shadowRadius: 8,
            elevation: 3,
        },

        // Map styles 
        mapContainer: {
            borderRadius: 12,
            overflow: 'hidden',
            marginVertical: 12,
            borderWidth: 1,
            borderColor: colors.border,
        },
        map: {
            width: '100%',
            height: 200,
        },
        markerContainer: {
            width: 20,
            height: 20,
            borderRadius: 10,
            backgroundColor: colors.accent.primary,
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 2,
            borderColor: '#ffffff',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 4,
            elevation: 4,
        },
        markerDot: {
            width: 8,
            height: 8,
            borderRadius: 4,
            backgroundColor: '#ffffff',
        },
        userMarkerContainer: {
            width: 24,
            height: 24,
            borderRadius: 12,
            backgroundColor: '#ef4444',
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 2,
            borderColor: '#ffffff',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 4,
            elevation: 4,
        },
        userMarkerDot: {
            width: 10,
            height: 10,
            borderRadius: 5,
            backgroundColor: '#ffffff',
        },
        userMarkerPulse: {
            position: 'absolute',
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: 'rgba(239, 68, 68, 0.3)',
        },
        mapLegend: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: 12,
            padding: 8,
            backgroundColor: isDark ? colors.card : '#f8fafc',
            borderTopWidth: 1,
            borderTopColor: colors.border,
        },
        legendItem: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 4,
        },
        legendDot: {
            width: 10,
            height: 10,
            borderRadius: 5,
            backgroundColor: colors.accent.primary,
        },
        legendCircle: {
            width: 10,
            height: 10,
            borderRadius: 5,
            borderWidth: 2,
            borderColor: colors.accent.primary,
            backgroundColor: 'transparent',
        },
        legendText: {
            fontSize: 10,
            color: colors.sidebar.text.muted,
        },
        distanceInfo: {
            backgroundColor: isDark ? colors.card : '#f8fafc',
            borderRadius: 8,
            padding: 12,
            marginTop: 8,
        },
        distanceRow: {
            marginTop: 4,
            paddingTop: 4,
            borderTopWidth: 1,
            borderTopColor: colors.border,
        },
        selectedImagePreview: {
            width: 80,
            height: 80,
            borderRadius: 12,
            marginTop: 8,
            alignSelf: 'center',
        },
        eventsListContainer: {
            flex: 1,
            minHeight: 200,
        },
        paginatedTitleRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: 4,
        },
        paginatedBadgeContainer: {
            flexDirection: 'row',
            gap: 4,
            marginLeft: 8,
        },
        paginatedLocationRow: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        glassModalOverlayTouch: {
            flex: 1,
        },
        glassModalCentered: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            padding: 20,
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
        },
        glassModalContainer: {
            width: '100%',
            maxWidth: 500,
            maxHeight: '85%',
            borderRadius: 28,
            overflow: 'hidden',
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.3)',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 10 },
            shadowOpacity: 0.3,
            shadowRadius: 20,
            elevation: 15,
        },
        glassModalGradientHeader: {
            borderTopLeftRadius: 28,
            borderTopRightRadius: 28,
            overflow: 'hidden',
        },
        glassModalHeaderLeft: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
        },
        glassModalIconContainer: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: 'rgba(59,130,246,0.15)',
            justifyContent: 'center',
            alignItems: 'center',
        },
        glassModalIconContainerMobile: {
            width: 32,
            height: 32,
        },

        glassModalSubtitle: {
            fontSize: 13,
            marginTop: 2,
        },
        glassModalCloseButton: {
            padding: 4,
        },
        glassModalScrollContent: {
            paddingBottom: 20,
        },
        glassModalFormSection: {
            marginHorizontal: 16,
            marginVertical: 12,
            borderRadius: 20,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.2)',
            overflow: 'hidden',
            backgroundColor: 'transparent',
        },
        glassFormGroup: {
            marginHorizontal: 16,
            marginTop: 16,
        },
        glassFormLabel: {
            fontSize: 14,
            fontWeight: '600',
            marginBottom: 8,
        },
        glassFormInput: {
            backgroundColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.05)',
            borderRadius: 12,
            paddingHorizontal: 16,
            paddingVertical: 12,
            fontSize: 16,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.2)',
        },
        glassFormInputMobile: {
            fontSize: 14,
            paddingVertical: 10,
        },
        glassTextArea: {
            minHeight: 100,
            textAlignVertical: 'top',
        },
        glassFormActions: {
            flexDirection: 'row',
            gap: 12,
            marginHorizontal: 16,
            marginTop: 24,
            marginBottom: 16,
        },
        glassFormActionsMobile: {
            flexDirection: 'column',
            gap: 10,
        },
        glassSubmitButton: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            backgroundColor: colors.accent.primary,
            paddingVertical: 12,
            borderRadius: 40,
            shadowColor: colors.accent.primary,
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            elevation: 4,
        },
        glassSubmitButtonMobile: {
            paddingVertical: 10,
        },
        glassSubmitButtonDisabled: {
            opacity: 0.5,
        },
        glassSubmitButtonText: {
            color: '#ffffff',
            fontSize: 16,
            fontWeight: '600',
        },
        glassSubmitButtonTextMobile: {
            fontSize: 14,
        },
        glassCancelButton: {
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
            paddingVertical: 12,
            borderRadius: 40,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.3)',
            backgroundColor: 'rgba(255,255,255,0.1)',
        },
        glassCancelButtonMobile: {
            paddingVertical: 10,
        },
        glassCancelButtonText: {
            fontSize: 16,
            fontWeight: '500',
        },
        glassCancelButtonTextMobile: {
            fontSize: 14,
        },
        glassFormHelperText: {
            fontSize: 12,
            marginTop: 4,
            marginLeft: 4,
        },

        paginatedItemMobile: { padding: 10, gap: 8 },
        paginatedTitleMobile: { fontSize: 13 },
        paginatedDateMobile: { fontSize: 10 },
        paginatedEditButtonMobile: { width: 28, height: 28 },
        paginatedDeleteButtonMobile: { width: 28, height: 28 },
        searchResultItemMobile: { padding: 10 },
        searchResultTitleMobile: { fontSize: 13 },
        searchResultLocationMobile: { fontSize: 10 },
        searchResultEditButtonMobile: { width: 26, height: 26 },
        searchResultDeleteButtonMobile: { width: 26, height: 26 },
        searchResultDescriptionMobile: { fontSize: 12, lineHeight: 16 },
        searchResultDateTextMobile: { fontSize: 10 },
        searchResultAttendeesTextMobile: { fontSize: 9 },
        paginationContainerMobile: { gap: 12, paddingTop: 12, marginTop: 12 },
        paginationButtonMobile: { paddingHorizontal: 8, paddingVertical: 6 },
        pageInfoTextMobile: { fontSize: 12 },
        modernModalContainerMobile: { width: '95%', maxWidth: 400 },
        modernModalHeaderMobile: { paddingHorizontal: 15, paddingVertical: 12 },
        modernModalHeaderLeftMobile: { gap: 8 },
        modernModalIconContainerMobile: { width: 32, height: 32 },
        modernModalTitleMobile: { fontSize: 16 },
        modernModalSubtitleMobile: { fontSize: 10 },
        modernModalCloseButtonMobile: { width: 32, height: 32 },
        modernModalContentMobile: { padding: 15, maxHeight: 500 },
        modernFormLabelMobile: { fontSize: 13 },
        modernFormActionsMobile: { gap: 8, marginTop: 20 },
        modernSubmitButtonMobile: { paddingVertical: 12 },
        modernSubmitButtonTextMobile: { fontSize: 14 },
        modernCancelButtonMobile: { paddingVertical: 12 },
        modernCancelButtonTextMobile: { fontSize: 14 },
        modernDetailImageContainerMobile: { height: 100 },
        modernDetailTitleMobile: { fontSize: 16 },
        modernDetailTextMobile: { fontSize: 13, lineHeight: 18, padding: 10 },
        headerGradientMobile: { paddingTop: 10, paddingBottom: 5, paddingHorizontal: 15 },
        headerContentMobile: { marginBottom: 15 },
        greetingTextMobile: { fontSize: 12 },
        userNameMobile: { fontSize: 20 },
        roleTextMobile: { fontSize: 10 },
        profileButtonMobile: { width: 40, height: 40 },
        profileInitialsMobile: { fontSize: 16 },
        dateSectionMobile: { marginTop: -5 },
        dateContainerMobile: { marginLeft: -5, marginTop: -15, paddingHorizontal: 5, paddingVertical: 4 },
        dateTextMobile: { fontSize: 9 },
        headerActionMobile: { width: 36, height: 36 },
        statsGridMobile: { gap: 10, padding: 15, marginTop: -15 },
        statCardMobile: { padding: 12, minWidth: '30%' },
        statIconContainerMobile: { width: 36, height: 36 },
        statNumberMobile: { fontSize: 22 },
        statLabelMobile: { fontSize: 10 },
        mainContentMobile: { flexDirection: 'column', padding: 15, gap: 15 },
        leftGridMobile: { width: '100%', marginBottom: 15 },
        leftHeaderMobile: { marginBottom: 12 },
        leftTitleMobile: { fontSize: 16 },
        leftControlsMobile: { gap: 8 },
        eventCountMobile: { fontSize: 12, paddingHorizontal: 8, paddingVertical: 3 },
        leftFiltersMobile: { marginRight: -15 },
        leftFilterButtonMobile: { paddingHorizontal: 10, paddingVertical: 5, marginRight: 6 },
        leftFilterButtonTextMobile: { fontSize: 11 },
        loadingTextMobile: { fontSize: 11 },
        emptyStateMobile: { paddingVertical: 30 },
        emptyStateIconMobile: { width: 60, height: 60, borderRadius: 30 },
        emptyStateTitleMobile: { fontSize: 16 },
        emptyStateTextMobile: { fontSize: 12, maxWidth: 250 },
        rightGridMobile: { width: '100%' },
        rightHeaderMobile: { marginBottom: 15 },
        searchTitleMobile: { fontSize: 16, marginBottom: 12 },
        searchContainerMobile: { paddingHorizontal: 12, paddingVertical: 10 },
        searchInputMobile: { marginLeft: 8, fontSize: 13 },
        searchStatsMobile: { marginBottom: 12 },
        resultsCountMobile: { fontSize: 13 },
    });
};