import { Dimensions, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    background: {
        flex: 1,
        backgroundColor: '#000',
    },
    backgroundImage: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    keyboardView: {
        flex: 1,
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    card: {
        width: width * 0.9,
        maxWidth: 400,
        backgroundColor: 'rgba(0, 0, 0, 0.65)',
        borderRadius: 28,
        padding: 28,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 8,
        },
        shadowOpacity: 0.4,
        shadowRadius: 16,
        elevation: 10,
    },
    logoContainer: {
        alignItems: 'center',
        marginBottom: 20,
    },
    logo: {
        width: 80,
        height: 80,
        borderRadius: 40,
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#FFFFFF',
        textAlign: 'center',
        marginBottom: 6,
        letterSpacing: 0.5,
    },
    subtitle: {
        fontSize: 15,
        color: 'rgba(255, 255, 255, 0.8)',
        textAlign: 'center',
        marginBottom: 32,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.15)',
        height: 56,
    },
    inputIcon: {
        paddingLeft: 16,
    },
    input: {
        flex: 1,
        color: '#FFFFFF',
        fontSize: 16,
        paddingHorizontal: 12,
        paddingVertical: 14,
        fontWeight: '500',
    },
    eyeIcon: {
        paddingRight: 16,
    },
    checkboxContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 24,
        marginTop: 8,
    },
    checkbox: {
        width: 24,
        height: 24,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: 'rgba(255, 255, 255, 0.5)',
        marginRight: 12,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.3)',
    },
    checkboxChecked: {
        backgroundColor: '#FFB74D',
        borderColor: '#FFB74D',
    },
    checkboxLabel: {
        fontSize: 16,
        color: '#FFFFFF',
        fontWeight: '500',
    },
    button: {
        backgroundColor: '#FFB74D',
        borderRadius: 30,
        height: 56,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        shadowColor: '#FFB74D',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
        width: '100%',
    },
    buttonText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#000000',
        letterSpacing: 1,
    },
    disabled: {
        opacity: 0.5,
    },
 
    forgotLink: {
        alignItems: 'center',
        marginBottom: 24,
    },
    forgotText: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.9)',
        fontWeight: '500',
        textDecorationLine: 'underline',
        textDecorationColor: 'rgba(255, 255, 255, 0.3)',
    },
    backLink: {
        alignItems: 'center',
        paddingVertical: 8,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255, 255, 255, 0.1)',
        marginTop: 8,
    },
    backLinkText: {
        fontSize: 15,
        color: 'rgba(255, 255, 255, 0.7)',
        fontWeight: '500',
        paddingTop: 8,
    },
    error: {
        color: '#FF6B6B',
        fontSize: 14,
        textAlign: 'center',
        marginBottom: 16,
        backgroundColor: 'rgba(255, 107, 107, 0.15)',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 10,
        overflow: 'hidden',
        fontWeight: '500',
        borderWidth: 1,
        borderColor: 'rgba(255, 107, 107, 0.3)',
    },
    inputDisabled: {
        opacity: 0.6,
    },
    
    floatingLabelContainer: {
        position: 'relative',
        height: 56,
    },
    floatingLabelWrapper: {
        flex: 1,
        height: '100%',
        justifyContent: 'center',
    },
    floatingLabel: {
        position: 'absolute',
        left: 12,
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 16,
        fontWeight: '500',
        backgroundColor: 'transparent',
        zIndex: 1,
        pointerEvents: 'none',
    },
    inputWithIcon: {
        paddingTop: 18,
        paddingBottom: 6,
        paddingLeft: 12,
        fontSize: 16,
    },
});