import { StyleSheet } from 'react-native'
import { ThemeColors } from '../../context/ThemeContext'

export const createStudentAnnouncementStyles = (
  colors: ThemeColors,
  isDark: boolean,
  isMobile: boolean,
  isTablet: boolean,
  isDesktop: boolean
) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      paddingTop: isMobile ? 40 : 48,
      paddingBottom: isMobile ? 20 : 24,
      paddingHorizontal: isMobile ? 16 : 24,
      borderBottomLeftRadius: isMobile ? 24 : 32,
      borderBottomRightRadius: isMobile ? 24 : 32,
    },
    headerTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: isMobile ? 16 : 20,
    },
    greeting: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.muted,
      marginBottom: 2,
    },
    userName: {
      fontSize: isMobile ? 20 : 24,
      fontWeight: '700',
      color: '#ffffff',
      marginBottom: 2,
    },
    role: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.muted,
      fontWeight: '500',
    },
    profileButton: {
      width: isMobile ? 44 : 48,
      height: isMobile ? 44 : 48,
      borderRadius: isMobile ? 22 : 24,
      borderWidth: 2,
      borderColor: '#ffffff',
      overflow: 'hidden',
    },
    profileImage: {
      width: '100%',
      height: '100%',
    },
    profileFallback: {
      backgroundColor: colors.accent.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    profileInitials: {
      color: '#ffffff',
      fontSize: isMobile ? 16 : 18,
      fontWeight: '600',
    },
    headerBottom: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    dateContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: isMobile ? 8 : 10,
      paddingVertical: isMobile ? 4 : 6,
      marginTop: -20,
      marginLeft: -6,
    },
    dateText: {
      fontSize: isMobile ? 10 : 12,
      color: '#ffffff',
      fontWeight: '500',
    },
    statsContainer: {
      marginTop: -20,
      marginHorizontal: isMobile ? 16 : 24,
      marginBottom: isMobile ? 16 : 20,
    },
    statsScroll: {
      gap: isMobile ? 8 : 12,
      paddingVertical: 4,
      paddingRight: isMobile ? 8 : 12,
    },
    statCard: {
      width: isMobile ? 90 : 100,
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: isMobile ? 12 : 14,
      borderLeftWidth: 3,
      borderLeftColor: colors.accent.primary,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.3 : 0.05,
      shadowRadius: 8,
      elevation: 2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statIcon: {
      width: isMobile ? 28 : 32,
      height: isMobile ? 28 : 32,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 8,
    },
    statNumber: {
      fontSize: isMobile ? 16 : 18,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 2,
    },
    statLabel: {
      fontSize: isMobile ? 10 : 12,
      color: colors.sidebar.text.secondary,
      fontWeight: '500',
    },
    searchSection: {
      paddingHorizontal: isMobile ? 16 : 24,
      marginBottom: isMobile ? 12 : 16,
    },
    searchBar: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: isMobile ? 6 : 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchInput: {
      flex: 1,
      marginLeft: 10,
      fontSize: isMobile ? 12 : 14,
      color: colors.text,
      paddingVertical: isMobile ? 6 : 8,
    },
    searchClear: {
      padding: 4,
    },
    filterSection: {
      marginBottom: isMobile ? 12 : 16,
    },
    filterScroll: {
      paddingHorizontal: isMobile ? 16 : 24,
      gap: 8,
    },
    filterChip: {
      paddingHorizontal: isMobile ? 12 : 16,
      paddingVertical: isMobile ? 6 : 8,
      borderRadius: 20,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
    },
    filterChipActive: {
      backgroundColor: colors.accent.primary,
      borderColor: colors.accent.primary,
    },
    filterChipText: {
      fontSize: isMobile ? 11 : 13,
      color: colors.sidebar.text.secondary,
      fontWeight: '500',
    },
    filterChipTextActive: {
      color: '#ffffff',
      fontWeight: '600',
    },
    listContainer: {
      padding: isMobile ? 16 : 24,
      paddingTop: 0,
      gap: isMobile ? 8 : 12,
      paddingBottom: 20,
    },
    card: {
      backgroundColor: colors.card,
      borderRadius: 16,
      flexDirection: 'row',
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.3 : 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    cardAbsoluteBar: {
      position: 'absolute',
      left: 0,
      top: 0,
      bottom: 0,
      width: isMobile ? 30 : 60,
      borderTopLeftRadius: 16,
      borderBottomLeftRadius: 16,
    },
    cardContent: {
      flex: 1,
      padding: isMobile ? 12 : 16,
    },
    cardHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 0,
    },
    cardHeaderRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    cardTitle: {
      fontSize: isMobile ? 14 : 16,
      fontWeight: '600',
      color: colors.text,
      flexShrink: 1,
      marginRight: 8,
    },
    cardTime: {
      fontSize: isMobile ? 10 : 12,
      color: colors.sidebar.text.muted,
    },
    priorityDotSmall: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    cardMessage: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.secondary,
      lineHeight: 18,
      marginTop: 4,
    },
    badge: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
    },
    badgeText: {
      fontSize: 9,
      fontWeight: '700',
      color: '#ffffff',
      textTransform: 'uppercase',
    },
    emptyState: {
      alignItems: 'center',
      paddingVertical: 60,
      paddingHorizontal: 20,
    },
    emptyStateIcon: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
    },
    emptyStateTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: colors.sidebar.text.secondary,
      marginBottom: 8,
    },
    emptyStateText: {
      fontSize: 14,
      color: colors.sidebar.text.muted,
      textAlign: 'center',
    },
    resultsInfo: {
      paddingHorizontal: isMobile ? 16 : 24,
      marginBottom: 8,
    },
    resultsText: {
      fontSize: isMobile ? 11 : 13,
      color: colors.sidebar.text.secondary,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    loadingText: {
      marginTop: 12,
      fontSize: 14,
      color: colors.sidebar.text.secondary,
    },
    errorContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 20,
    },
    errorText: {
      fontSize: 14,
      color: '#DC2626',
      textAlign: 'center',
      marginTop: 8,
    },
    paginationWrapper: {
      paddingVertical: 16,
      paddingHorizontal: isMobile ? 16 : 24,
    },
    paginationContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.3 : 0.05,
      shadowRadius: 8,
      elevation: 2,
      marginBottom: 100,
    },
    paginationButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: colors.border,
      gap: 4,
    },
    paginationButtonDisabled: {
      opacity: 0.5,
    },
    paginationText: {
      fontSize: 13,
      fontWeight: '500',
      color: colors.text,
    },
    paginationTextDisabled: {
      color: colors.sidebar.text.muted,
    },
    paginationPageInfo: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'flex-end',
    },
    detailModalContainer: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      maxHeight: '85%',
    },
    detailModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    detailModalHeaderLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    detailPriorityIndicator: {
      width: 4,
      height: 24,
      borderRadius: 2,
    },
    detailModalTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: colors.text,
    },
    detailModalClose: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    detailModalContent: {
      padding: 20,
    },
    detailBadges: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 16,
    },
    detailBadge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 6,
    },
    detailBadgeText: {
      fontSize: 10,
      fontWeight: '700',
      color: '#ffffff',
      textTransform: 'uppercase',
    },
    detailTitle: {
      fontSize: isMobile ? 18 : 22,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 12,
      lineHeight: 26,
    },
    detailMeta: {
      flexDirection: 'row',
      gap: 16,
      marginBottom: 20,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    detailMetaItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    detailMetaText: {
      fontSize: 13,
      color: colors.sidebar.text.secondary,
    },
    detailMessageContainer: {
      backgroundColor: colors.border,
      borderRadius: 12,
      padding: 16,
      marginBottom: 20,
    },
    detailMessage: {
      fontSize: isMobile ? 14 : 16,
      color: colors.text,
      lineHeight: 24,
    },
    cardNumberContainer: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    cardNumberBadge: {
      width: isMobile ? 24 : 28,
      height: isMobile ? 24 : 28,
      borderRadius: isMobile ? 12 : 14,

      justifyContent: 'center',
      alignItems: 'center',
    },
    cardNumberText: {
      fontSize: isMobile ? 10 : 12,
      fontWeight: '600',
      color: colors.text,
    },
  })
}
