import { StyleSheet } from 'react-native';

export const studentDashboardStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    contentArea: {
        flex: 1,
    },
    overviewContainer: {
        flex: 1,
    },
    headerGradient: {
        paddingHorizontal: 16,
        paddingTop: 50,
        paddingBottom: 5,
        borderBottomLeftRadius: 24,
        borderBottomRightRadius: 24,
    },
    headerContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    greetingText: {
        fontSize: 13,
        color: '#94a3b8',
        fontFamily: 'Inter-Regular',
    },
    userName: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#ffffff',
        marginTop: 2,
    },
    roleText: {
        fontSize: 13,
        color: '#0ea5e9',
        marginTop: 4,
    },
    profileButton: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: '#ffffff20',
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
    },
    profileImage: {
        width: 56,
        height: 56,
        borderRadius: 28,
    },
    profileFallback: {
        backgroundColor: '#0ea5e9',
        justifyContent: 'center',
        alignItems: 'center',
    },
    profileInitials: {
        fontSize: 24,
        fontWeight: '600',
        color: '#ffffff',
    },
    dateSection: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 16,
    },
    dateContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    dateText: {
        fontSize: 12,
        color: '#94a3b8',
    },
    headerActions: {
        flexDirection: 'row',
        gap: 12,
    },
    headerAction: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#ffffff20',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    notificationBadge: {
        position: 'absolute',
        top: -4,
        right: -4,
        backgroundColor: '#ef4444',
        borderRadius: 10,
        minWidth: 18,
        height: 18,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 4,
    },
    notificationBadgeText: {
        color: '#ffffff',
        fontSize: 10,
        fontWeight: 'bold',
    },
    statsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        paddingHorizontal: 12,
        marginTop: 0,
        gap: 12,
        justifyContent: 'space-between',
    },
    statCard: {
        backgroundColor: '#ffffff',
        borderRadius: 20,
        padding: 16,
        width: '30%',
        minWidth: 100,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
        borderLeftWidth: 4,
        marginTop: 12,
    },
    statCardHeader: {
        marginBottom: 12,
    },
    statIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    statNumber: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#0f172a',
    },
    statLabel: {
        fontSize: 13,
        color: '#64748b',
        marginTop: 4,
    },
    quickActionsSection: {
        marginTop: 24,
        paddingHorizontal: 16,
    },
    quickActionsTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#0f172a',
        marginBottom: 12,
    },
    quickActionsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        justifyContent: 'space-between',
    },
    quickActionCard: {
        width: '30%',
        aspectRatio: 1,
        borderRadius: 20,
        overflow: 'hidden',
    },
    quickActionGradient: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 12,
    },
    quickActionText: {
        fontSize: 12,
        color: '#ffffff',
        marginTop: 8,
        textAlign: 'center',
    },
    twoColumnLayout: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        paddingHorizontal: 16,
        marginTop: 24,
        gap: 16,
        paddingBottom: 30,
    },
    column: {
        flex: 1,
        minWidth: 280,
    },
    upcomingColumn: {
        flex: 1,
    },
    upcomingCard: {
        backgroundColor: '#ffffff',
        borderRadius: 24,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    upcomingHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    upcomingTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#0f172a',
    },
    viewAllText: {
        fontSize: 13,
        color: '#0ea5e9',
        fontWeight: '500',
    },
    upcomingList: {
        gap: 12,
    },
    upcomingItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    eventDate: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: '#f1f5f9',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    eventDay: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#0f172a',
    },
    eventMonth: {
        fontSize: 10,
        color: '#64748b',
    },
    eventInfo: {
        flex: 1,
    },
    eventName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#0f172a',
    },
    eventTime: {
        fontSize: 12,
        color: '#64748b',
        marginTop: 2,
    },
    loadingContainer: {
        alignItems: 'center',
        paddingVertical: 24,
    },
    loadingText: {
        fontSize: 13,
        color: '#94a3b8',
        marginTop: 8,
    },
    emptyContainer: {
        alignItems: 'center',
        paddingVertical: 24,
    },
    emptyText: {
        fontSize: 14,
        color: '#94a3b8',
        marginTop: 8,
    },
    createButton: {
        marginTop: 12,
        paddingVertical: 8,
        paddingHorizontal: 16,
        backgroundColor: '#0ea5e9',
        borderRadius: 20,
    },
    createButtonText: {
        fontSize: 13,
        color: '#ffffff',
        fontWeight: '600',
    },
    announcementCard: {
        backgroundColor: '#ffffff',
        borderRadius: 24,
        padding: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    announcementHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    announcementTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#0f172a',
    },
    announcementList: {
        gap: 12,
    },
    announcementItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    announcementBadge: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    announcementContent: {
        flex: 1,
    },
    announcementText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#0f172a',
    },
    announcementTime: {
        fontSize: 11,
        color: '#94a3b8',
        marginTop: 2,
    },
    registeredBadge: {
    fontSize: 11,
    color: '#10b981',
    fontWeight: '600',
    marginTop: 2,
},
});