import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../context/ThemeContext';

export const createProfileStyles = (
  colors: ThemeColors,
  isDark: boolean,
  isMobile: boolean,
  isTablet: boolean,
  isDesktop: boolean
) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      paddingTop: isMobile ? 40 : 48,
      paddingHorizontal: isMobile ? 16 : 24,
    },
    profileCard: {
      backgroundColor: colors.card,
      borderRadius: 24,
      padding: isMobile ? 20 : 24,
      alignItems: 'center',
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.3 : 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    avatarContainer: {
      position: 'relative',
      marginBottom: 16,
    },
    avatar: {
      width: isMobile ? 80 : 100,
      height: isMobile ? 80 : 100,
      borderRadius: isMobile ? 40 : 50,
      backgroundColor: colors.accent.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    avatarImage: {
      width: isMobile ? 80 : 100,
      height: isMobile ? 80 : 100,
      borderRadius: isMobile ? 40 : 50,
    },
    avatarText: {
      fontSize: isMobile ? 32 : 40,
      fontWeight: '600',
      color: '#ffffff',
    },
    cameraIcon: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: colors.accent.primary,
      width: isMobile ? 28 : 32,
      height: isMobile ? 28 : 32,
      borderRadius: isMobile ? 14 : 16,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 3,
      borderColor: colors.card,
    },
    name: {
      fontSize: isMobile ? 18 : 20,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 4,
    },
    id: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.secondary,
      marginBottom: 4,
    },
    course: {
      fontSize: isMobile ? 14 : 16,
      fontWeight: '500',
      color: colors.text,
      marginBottom: 2,
    },
    yearLevel: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.secondary,
    },
    section: {
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: isMobile ? 14 : 16,
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: isDark ? 0.3 : 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    sectionTitle: {
      fontSize: isMobile ? 15 : 16,
      fontWeight: '600',
      color: colors.text,
      marginRight: 8,
    },
    eventsCount: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.secondary,
    },
    loading: {
      marginVertical: 20,
    },
    emptyState: {
      alignItems: 'center',
      paddingVertical: 24,
    },
    emptyStateText: {
      fontSize: isMobile ? 13 : 14,
      color: colors.sidebar.text.secondary,
      marginTop: 8,
      textAlign: 'center',
    },
    emptyStateSubtext: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.muted,
      marginTop: 8,
      textAlign: 'center',
    },
    eventsList: {
      gap: 12,
    },
    eventItem: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
    },
    attendedEventItem: {
      borderLeftWidth: 3,
      borderLeftColor: '#10b981',
    },
    eventIcon: {
      width: 36,
      height: 36,
      borderRadius: 8,
      backgroundColor: isDark ? `${colors.accent.primary}20` : '#fee2e2',
      justifyContent: 'center',
      alignItems: 'center',
    },
    eventDetails: {
      flex: 1,
    },
    eventTitle: {
      fontSize: isMobile ? 14 : 15,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 2,
    },
    eventDate: {
      fontSize: isMobile ? 11 : 12,
      color: colors.sidebar.text.secondary,
      marginBottom: 2,
    },
    deadlineText: {
      fontSize: isMobile ? 10 : 11,
      color: '#dc2626',
      fontWeight: '500',
    },
    scannedAtText: {
      fontSize: isMobile ? 11 : 12,
      color: '#10b981',
      marginTop: 4,
      fontWeight: '500',
    },
    moreEventsText: {
      fontSize: isMobile ? 12 : 13,
      color: colors.accent.primary,
      marginTop: 8,
      textAlign: 'center',
    },
    menu: {
      marginTop: 4,
    },
    menuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    menuText: {
      flex: 1,
      fontSize: isMobile ? 14 : 15,
      color: colors.text,
      marginLeft: 12,
    },
    logoutButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 14,
      marginBottom: 150,
      borderWidth: 1,
      borderColor: '#fee2e2',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: isDark ? 0.3 : 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    logoutText: {
      fontSize: isMobile ? 14 : 15,
      fontWeight: '600',
      color: '#dc2626',
      marginLeft: 8,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 16,
    },
    aboutModal: {
      backgroundColor: colors.card,
      borderRadius: 24,
      width: '100%',
      maxHeight: '80%',
      padding: 20,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    modalTitle: {
      fontSize: isMobile ? 16 : 18,
      fontWeight: '700',
      color: colors.text,
    },
    modalSubtitle: {
      fontSize: isMobile ? 12 : 14,
      color: colors.sidebar.text.secondary,
      marginTop: 2,
    },
    aboutContent: {
      gap: 20,
    },
    aboutSection: {
      marginBottom: 16,
    },
    aboutDescription: {
      fontSize: isMobile ? 13 : 14,
      color: colors.text,
      lineHeight: 20,
    },
    organizationName: {
      fontSize: isMobile ? 14 : 16,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 12,
    },
    membersList: {
      gap: 12,
    },
    memberItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    memberAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.accent.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    memberAvatarImage: {
      width: 44,
      height: 44,
      borderRadius: 22,
    },
    memberAvatarText: {
      fontSize: 18,
      fontWeight: '600',
      color: '#ffffff',
    },
    memberInfo: {
      flex: 1,
    },
    memberName: {
      fontSize: isMobile ? 14 : 15,
      fontWeight: '600',
      color: colors.text,
    },
    memberRole: {
      fontSize: isMobile ? 11 : 12,
      color: colors.accent.primary,
      marginTop: 2,
    },
    memberEmail: {
      fontSize: isMobile ? 10 : 11,
      color: colors.sidebar.text.secondary,
      marginTop: 2,
    },
    sectionLabel: {
      fontSize: isMobile ? 13 : 14,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 8,
    },
    submittedToCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.border,
      borderRadius: 12,
      padding: 12,
      gap: 12,
    },
    submittedToInfo: {
      flex: 1,
    },
    submittedToName: {
      fontSize: isMobile ? 14 : 15,
      fontWeight: '600',
      color: colors.text,
    },
    submittedToDepartment: {
      fontSize: isMobile ? 12 : 13,
      color: colors.sidebar.text.secondary,
      marginTop: 2,
    },
    submittedToInstitution: {
      fontSize: isMobile ? 11 : 12,
      color: colors.sidebar.text.muted,
      marginTop: 2,
    },
    versionSection: {
      alignItems: 'center',
      marginTop: 8,
    },
    versionText: {
      fontSize: isMobile ? 11 : 12,
      color: colors.sidebar.text.muted,
    },
    imageOptions: {
      backgroundColor: colors.card,
      borderRadius: 24,
      padding: 20,
      width: '100%',
      maxWidth: 400,
    },
    optionsTitle: {
      fontSize: isMobile ? 16 : 18,
      fontWeight: '600',
      color: colors.text,
      textAlign: 'center',
      marginBottom: 20,
    },
    optionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 12,
      backgroundColor: colors.border,
      marginBottom: 8,
    },
    optionText: {
      fontSize: isMobile ? 14 : 15,
      color: colors.text,
    },
    removeButton: {
      backgroundColor: '#fee2e2',
    },
    removeText: {
      color: '#dc2626',
    },
    cancelButton: {
      marginTop: 12,
      paddingVertical: 14,
      alignItems: 'center',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    cancelText: {
      fontSize: isMobile ? 14 : 15,
      fontWeight: '600',
      color: colors.sidebar.text.secondary,
    },
    tabContainer: {
      flexDirection: 'row',
      marginBottom: 16,
      backgroundColor: colors.border,
      borderRadius: 12,
      padding: 4,
    },
    tab: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 8,
      gap: 6,
    },
    activeTab: {
      backgroundColor: colors.card,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: isDark ? 0.3 : 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    tabText: {
      fontSize: isMobile ? 13 : 14,
      fontWeight: '600',
      color: colors.sidebar.text.secondary,
    },
    activeTabText: {
      color: colors.text,
    },
    badge: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 12,
      marginLeft: 4,
    },
    badgeText: {
      fontSize: isMobile ? 11 : 12,
      fontWeight: '700',
    },
    penaltyBadge: {
      position: 'absolute',
      top: 12,
      right: 12,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#ef4444',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 16,
      gap: 4,
    },
    penaltyBadgeText: {
      color: '#ffffff',
      fontSize: isMobile ? 11 : 12,
      fontWeight: '600',
    },
    menuIconContainer: {
      position: 'relative',
    },
    menuBadge: {
      position: 'absolute',
      top: -6,
      right: -6,
      backgroundColor: '#ef4444',
      width: 18,
      height: 18,
      borderRadius: 9,
      justifyContent: 'center',
      alignItems: 'center',
    },
    menuBadgeText: {
      color: '#ffffff',
      fontSize: 10,
      fontWeight: 'bold',
    },
    penaltyCard: {
      backgroundColor: colors.border,
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      borderLeftWidth: 4,
      borderLeftColor: colors.accent.primary,
    },
    penaltyCardOverdue: {
      borderLeftColor: '#dc2626',
      backgroundColor: '#fef2f2',
    },
    penaltyHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 8,
    },
    penaltyEventTitle: {
      fontSize: isMobile ? 15 : 16,
      fontWeight: '600',
      color: colors.text,
      flex: 1,
      marginRight: 8,
    },
    penaltyStatusBadge: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 12,
      marginLeft: 8,
    },
    penaltyStatusText: {
      fontSize: isMobile ? 9 : 10,
      fontWeight: '600',
    },
    // keep these for consistency, but they are not directly used in the component's styles (they use inline)
    // we can keep them as is or remove; for safety we include them but they may be unused
    settingsSection: {
      paddingHorizontal: 20,
      paddingTop: 8,
    },
    settingsSectionTitle: {
      fontSize: isMobile ? 15 : 16,
      fontWeight: '600',
      marginBottom: 12,
      color: colors.text,
    },
    settingsOption: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    settingsOptionLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    settingsOptionText: {
      fontSize: isMobile ? 14 : 16,
      color: colors.text,
    },
    // additional styles from original that were not fully covered
    penaltyType: {
      fontSize: isMobile ? 12 : 13,
      color: colors.sidebar.text.secondary,
      marginBottom: 12,
      textTransform: 'capitalize',
    },
    penaltySection: {
      marginBottom: 12,
    },
    penaltyLabel: {
      fontSize: isMobile ? 11 : 12,
      fontWeight: '600',
      color: colors.sidebar.text.muted,
      marginBottom: 4,
      textTransform: 'uppercase',
    },
    penaltyConsequences: {
      fontSize: isMobile ? 13 : 14,
      color: colors.text,
      lineHeight: 20,
    },
    deadlineRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 12,
    },
    deadlineTextOverdue: {
      color: '#dc2626',
      fontWeight: '600',
    },
    statusRow: {
      flexDirection: 'row',
      marginBottom: 12,
    },
    statusBadge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    statusPending: {
      backgroundColor: '#fef3c7',
    },
    statusCompleted: {
      backgroundColor: '#d1fae5',
    },
    statusExcused: {
      backgroundColor: '#e0e7ff',
    },
    statusText: {
      fontSize: isMobile ? 10 : 11,
      fontWeight: '700',
    },
    penaltyActions: {
      flexDirection: 'row',
      gap: 10,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    penaltyActionBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
      borderRadius: 8,
      gap: 6,
      borderWidth: 1,
    },
    completeBtn: {
      borderColor: '#10b981',
      backgroundColor: '#ecfdf5',
    },
    completeBtnText: {
      color: '#10b981',
      fontWeight: '600',
      fontSize: isMobile ? 12 : 13,
    },
    excuseBtn: {
      borderColor: '#f59e0b',
      backgroundColor: '#fffbeb',
    },
    excuseBtnText: {
      color: '#f59e0b',
      fontWeight: '600',
      fontSize: isMobile ? 12 : 13,
    },
    emptyStateTitle: {
      fontSize: isMobile ? 16 : 18,
      fontWeight: 'bold',
      color: '#10b981',
      marginTop: 16,
      marginBottom: 8,
    },
  });
};